// Stats for every named object
// tooltip: 3 quick stats shown on hover
// details: full list shown in the focus panel

export const OBJECT_DATA = {
  'Station 4': {
    type: 'Multi-Ring Orbital Station',
    tooltip: [
      { label: 'Rings',    value: '5 uniform' },
      { label: 'Diameter', value: '~880 m (ring)' },
      { label: 'Rotation', value: '~1.5 RPM' },
    ],
    details: [
      { label: 'Classification',  value: 'Multi-ring rotating station' },
      { label: 'Ring Count',       value: '5 identical levels' },
      { label: 'Ring Diameter',    value: '~880 m' },
      { label: 'Hub Height',       value: '~715 m' },
      { label: 'Spoke Corridors',  value: '8 per ring (40 total)' },
      { label: 'Rotation Rate',    value: '~1.5 RPM' },
      { label: 'Gravity (rim)',    value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',      value: '0 g (microgravity)' },
      { label: 'Crew Capacity',    value: 'Est. 2,000–5,000' },
      { label: 'Design',           value: 'Von Braun multi-wheel' },
    ],
  },

  'Station 3': {
    type: 'Advanced Orbital Colony',
    tooltip: [
      { label: 'Era',        value: 'c. 2230' },
      { label: 'Ring Levels', value: '5 (10 rings)' },
      { label: 'Crew',       value: '~10,000' },
    ],
    details: [
      { label: 'Classification',   value: 'Multi-ring orbital colony' },
      { label: 'Era',              value: 'c. 2230' },
      { label: 'Ring Levels',      value: '5 dual-ring levels' },
      { label: 'Max Ring Diameter', value: '~1,300 m (central level)' },
      { label: 'Spire Height',     value: '~760 m' },
      { label: 'Crew Capacity',    value: 'Est. 10,000' },
      { label: 'Gravity (rim)',    value: '~1 g (centrifugal)' },
      { label: 'Ring Rotation',    value: 'Counter-rotating pairs' },
      { label: 'Accelerator Ring', value: '~1,500 m diameter' },
      { label: 'Facilities',       value: 'Hangars, ag domes, labs' },
    ],
  },

  'Station 2': {
    type: 'Modular Orbital Station',
    tooltip: [
      { label: 'Orbit',       value: 'Low Earth Orbit' },
      { label: 'Ring Modules', value: '16 per ring' },
      { label: 'Rotation',    value: '~2 RPM' },
    ],
    details: [
      { label: 'Classification', value: 'Modular ring station' },
      { label: 'Ring Diameter',  value: '~274 m' },
      { label: 'Ring Modules',   value: '16 cylindrical segments' },
      { label: 'Rotation Rate',  value: '~2 RPM' },
      { label: 'Gravity (rim)',  value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',    value: '0 g (microgravity)' },
      { label: 'Crew Capacity',  value: 'Est. several hundred' },
      { label: 'Design',         value: 'Modular construction concept' },
    ],
  },

  'Station 1': {
    type: 'Orbital Space Station',
    tooltip: [
      { label: 'Orbit',    value: 'Low Earth Orbit' },
      { label: 'Diameter', value: '~274 m (ring)' },
      { label: 'Rotation', value: '~2 RPM' },
    ],
    details: [
      { label: 'Classification', value: 'Rotating ring station' },
      { label: 'Ring Diameter',  value: '~274 m' },
      { label: 'Rotation Rate',  value: '~2 RPM' },
      { label: 'Gravity (rim)',  value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',    value: '0 g (microgravity)' },
      { label: 'Crew Capacity',  value: 'Est. several hundred' },
      { label: 'Orbit Altitude', value: '~550 km' },
      { label: 'Design',         value: 'von Braun wheel concept' },
    ],
  },

  Sun: {
    type: 'G-Type Star',
    tooltip: [
      { label: 'Surface Temp', value: '5,778 K' },
      { label: 'Diameter', value: '1,392,700 km' },
      { label: 'Age', value: '4.6 Billion yrs' },
    ],
    details: [
      { label: 'Classification', value: 'G-type Main Sequence' },
      { label: 'Diameter', value: '1,392,700 km' },
      { label: 'Mass', value: '1.989 × 10³⁰ kg' },
      { label: 'Surface Temp', value: '5,778 K' },
      { label: 'Core Temp', value: '~15,000,000 K' },
      { label: 'Luminosity', value: '3.828 × 10²⁶ W' },
      { label: 'Composition', value: '73% H · 25% He' },
      { label: 'Age', value: '4.603 billion years' },
    ],
  },
  Mercury: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '4,879 km' },
      { label: 'Orbital Period', value: '88 days' },
      { label: 'Surface Temp', value: '-180 to 430°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '4,879 km' },
      { label: 'Mass', value: '3.285 × 10²³ kg' },
      { label: 'Distance from Sun', value: '0.39 AU' },
      { label: 'Orbital Period', value: '88 days' },
      { label: 'Rotation Period', value: '58.6 days' },
      { label: 'Surface Temp', value: '-180°C to 430°C' },
      { label: 'Known Moons', value: '0' },
    ],
  },
  Venus: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '12,104 km' },
      { label: 'Orbital Period', value: '225 days' },
      { label: 'Surface Temp', value: '465°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '12,104 km' },
      { label: 'Mass', value: '4.867 × 10²⁴ kg' },
      { label: 'Distance from Sun', value: '0.72 AU' },
      { label: 'Orbital Period', value: '225 days' },
      { label: 'Rotation Period', value: '243 days (retrograde)' },
      { label: 'Surface Temp', value: '465°C (avg)' },
      { label: 'Known Moons', value: '0' },
    ],
  },
  Earth: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '12,742 km' },
      { label: 'Orbital Period', value: '365.25 days' },
      { label: 'Surface Temp', value: '-88 to 58°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '12,742 km' },
      { label: 'Mass', value: '5.972 × 10²⁴ kg' },
      { label: 'Distance from Sun', value: '1.00 AU' },
      { label: 'Orbital Period', value: '365.25 days' },
      { label: 'Rotation Period', value: '23h 56m' },
      { label: 'Surface Temp', value: '-88°C to 58°C' },
      { label: 'Known Moons', value: '1' },
    ],
  },
  Moon: {
    type: 'Natural Satellite',
    tooltip: [
      { label: 'Diameter', value: '3,474 km' },
      { label: 'Orbital Period', value: '27.3 days' },
      { label: 'Distance', value: '384,400 km' },
    ],
    details: [
      { label: 'Classification', value: 'Natural Satellite' },
      { label: 'Diameter', value: '3,474 km' },
      { label: 'Mass', value: '7.342 × 10²² kg' },
      { label: 'Distance from Earth', value: '384,400 km' },
      { label: 'Orbital Period', value: '27.3 days' },
      { label: 'Rotation Period', value: '27.3 days (tidally locked)' },
      { label: 'Surface Temp', value: '-173°C to 127°C' },
      { label: 'Surface Gravity', value: '1.62 m/s²' },
    ],
  },
  Mars: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '6,779 km' },
      { label: 'Orbital Period', value: '687 days' },
      { label: 'Surface Temp', value: '-140 to 20°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '6,779 km' },
      { label: 'Mass', value: '6.39 × 10²³ kg' },
      { label: 'Distance from Sun', value: '1.52 AU' },
      { label: 'Orbital Period', value: '687 days' },
      { label: 'Rotation Period', value: '24h 37m' },
      { label: 'Surface Temp', value: '-140°C to 20°C' },
      { label: 'Known Moons', value: '2' },
    ],
  },
  Phobos: {
    type: 'Martian Moon',
    tooltip: [
      { label: 'Diameter', value: '~22 km' },
      { label: 'Orbital Period', value: '7.65 hours' },
      { label: 'Notable', value: 'Faster than Mars rotates' },
    ],
    details: [
      { label: 'Classification', value: 'Inner Martian Moon' },
      { label: 'Dimensions', value: '27 × 22 × 18 km' },
      { label: 'Mass', value: '1.066 × 10¹⁶ kg' },
      { label: 'Orbital Period', value: '7.651 hours' },
      { label: 'Distance from Mars', value: '9,376 km' },
      { label: 'Surface Temp', value: '-40°C (avg)' },
      { label: 'Notable', value: 'Orbits faster than Mars spins — rises in the west' },
      { label: 'Fate', value: 'Spiraling inward; will break apart in ~30–50 Myr' },
    ],
  },
  Deimos: {
    type: 'Martian Moon',
    tooltip: [
      { label: 'Diameter', value: '~12 km' },
      { label: 'Orbital Period', value: '1.263 days' },
      { label: 'Origin', value: 'Captured asteroid' },
    ],
    details: [
      { label: 'Classification', value: 'Outer Martian Moon' },
      { label: 'Dimensions', value: '15 × 12 × 11 km' },
      { label: 'Mass', value: '1.476 × 10¹⁵ kg' },
      { label: 'Orbital Period', value: '1.263 days' },
      { label: 'Distance from Mars', value: '23,460 km' },
      { label: 'Surface Temp', value: '-40°C (avg)' },
      { label: 'Origin', value: 'Likely captured C-type asteroid' },
      { label: 'Notable', value: 'Smooth, heavily cratered, very low gravity' },
    ],
  },
  Jupiter: {
    type: 'Gas Giant',
    tooltip: [
      { label: 'Diameter', value: '139,820 km' },
      { label: 'Orbital Period', value: '11.86 years' },
      { label: 'Known Moons', value: '95' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant' },
      { label: 'Diameter', value: '139,820 km' },
      { label: 'Mass', value: '1.898 × 10²⁷ kg' },
      { label: 'Distance from Sun', value: '5.20 AU' },
      { label: 'Orbital Period', value: '11.86 years' },
      { label: 'Rotation Period', value: '9h 56m' },
      { label: 'Avg Temperature', value: '-108°C' },
      { label: 'Known Moons', value: '95' },
    ],
  },
  Io: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '3,643 km' },
      { label: 'Orbital Period', value: '1.77 days' },
      { label: 'Surface Temp', value: '-130°C avg' },
    ],
    details: [
      { label: 'Classification', value: 'Volcanic Galilean Moon' },
      { label: 'Diameter', value: '3,643 km' },
      { label: 'Mass', value: '8.932 × 10²² kg' },
      { label: 'Orbital Period', value: '1.769 days' },
      { label: 'Distance from Jupiter', value: '421,800 km' },
      { label: 'Surface Temp', value: '-130°C (avg) / 1,600°C (lava)' },
      { label: 'Notable', value: 'Most volcanically active body in Solar System' },
      { label: 'Tidal heating by', value: 'Jupiter + Europa + Ganymede resonance' },
    ],
  },
  Europa: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '3,122 km' },
      { label: 'Orbital Period', value: '3.55 days' },
      { label: 'Ocean Depth', value: '~100 km' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Galilean Moon' },
      { label: 'Diameter', value: '3,122 km' },
      { label: 'Mass', value: '4.800 × 10²² kg' },
      { label: 'Orbital Period', value: '3.551 days' },
      { label: 'Distance from Jupiter', value: '671,100 km' },
      { label: 'Surface Temp', value: '-160°C (avg)' },
      { label: 'Notable', value: 'Subsurface liquid water ocean ~100 km deep' },
      { label: 'Habitability', value: 'Prime candidate for extraterrestrial life' },
    ],
  },
  Ganymede: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '5,268 km' },
      { label: 'Orbital Period', value: '7.15 days' },
      { label: 'Notable', value: 'Largest moon in Solar System' },
    ],
    details: [
      { label: 'Classification', value: 'Galilean Moon' },
      { label: 'Diameter', value: '5,268 km' },
      { label: 'Mass', value: '1.482 × 10²³ kg' },
      { label: 'Orbital Period', value: '7.155 days' },
      { label: 'Distance from Jupiter', value: '1,070,400 km' },
      { label: 'Surface Temp', value: '-163°C (avg)' },
      { label: 'Notable', value: 'Largest moon in Solar System; larger than Mercury' },
      { label: 'Magnetosphere', value: 'Only moon with its own magnetic field' },
    ],
  },
  Callisto: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '4,821 km' },
      { label: 'Orbital Period', value: '16.7 days' },
      { label: 'Surface', value: 'Most cratered in Solar System' },
    ],
    details: [
      { label: 'Classification', value: 'Galilean Moon' },
      { label: 'Diameter', value: '4,821 km' },
      { label: 'Mass', value: '1.076 × 10²³ kg' },
      { label: 'Orbital Period', value: '16.69 days' },
      { label: 'Distance from Jupiter', value: '1,882,700 km' },
      { label: 'Surface Temp', value: '-139°C (avg)' },
      { label: 'Notable', value: 'Most heavily cratered object in Solar System' },
      { label: 'Interior', value: 'Possible subsurface ocean; geologically inactive' },
    ],
  },
  Saturn: {
    type: 'Gas Giant',
    tooltip: [
      { label: 'Diameter', value: '116,460 km' },
      { label: 'Orbital Period', value: '29.46 years' },
      { label: 'Known Moons', value: '146' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant' },
      { label: 'Diameter', value: '116,460 km' },
      { label: 'Mass', value: '5.683 × 10²⁶ kg' },
      { label: 'Distance from Sun', value: '9.58 AU' },
      { label: 'Orbital Period', value: '29.46 years' },
      { label: 'Rotation Period', value: '10h 33m' },
      { label: 'Avg Temperature', value: '-139°C' },
      { label: 'Known Moons', value: '146' },
    ],
  },
  Mimas: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '396 km' },
      { label: 'Orbital Period', value: '0.942 days' },
      { label: 'Notable', value: '"Death Star" crater' },
    ],
    details: [
      { label: 'Classification', value: 'Small Saturnian Moon' },
      { label: 'Diameter', value: '396 km' },
      { label: 'Mass', value: '3.749 × 10¹⁹ kg' },
      { label: 'Orbital Period', value: '0.942 days' },
      { label: 'Distance from Saturn', value: '185,540 km' },
      { label: 'Surface Temp', value: '-209°C' },
      { label: 'Notable', value: 'Herschel crater = 130 km across ("Death Star")' },
      { label: 'Quirk', value: 'Resonance with Tethys locks orbital period 1:2' },
    ],
  },
  Enceladus: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '504 km' },
      { label: 'Orbital Period', value: '1.37 days' },
      { label: 'Notable', value: 'Active water geysers' },
    ],
    details: [
      { label: 'Classification', value: 'Active Icy Moon' },
      { label: 'Diameter', value: '504 km' },
      { label: 'Mass', value: '1.080 × 10²⁰ kg' },
      { label: 'Orbital Period', value: '1.370 days' },
      { label: 'Distance from Saturn', value: '238,040 km' },
      { label: 'Surface Temp', value: '-201°C (avg)' },
      { label: 'Notable', value: 'Active geysers erupt liquid water into space' },
      { label: 'Habitability', value: 'Subsurface ocean; prime life candidate' },
    ],
  },
  Tethys: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,062 km' },
      { label: 'Orbital Period', value: '1.888 days' },
      { label: 'Composition', value: 'Nearly pure water ice' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,062 km' },
      { label: 'Mass', value: '6.175 × 10²⁰ kg' },
      { label: 'Orbital Period', value: '1.888 days' },
      { label: 'Distance from Saturn', value: '294,670 km' },
      { label: 'Surface Temp', value: '-187°C' },
      { label: 'Composition', value: 'Nearly pure water ice' },
      { label: 'Notable', value: 'Ithaca Chasma — vast canyon system' },
    ],
  },
  Dione: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,123 km' },
      { label: 'Orbital Period', value: '2.737 days' },
      { label: 'Surface', value: 'Ice cliffs and wispy streaks' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,123 km' },
      { label: 'Mass', value: '1.096 × 10²¹ kg' },
      { label: 'Orbital Period', value: '2.737 days' },
      { label: 'Distance from Saturn', value: '377,400 km' },
      { label: 'Surface Temp', value: '-186°C' },
      { label: 'Notable', value: 'Bright ice cliffs and wispy linear features' },
      { label: 'Resonance', value: 'Locked 1:2 with Enceladus' },
    ],
  },
  Rhea: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,528 km' },
      { label: 'Orbital Period', value: '4.518 days' },
      { label: 'Notable', value: 'Second largest moon of Saturn' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,528 km' },
      { label: 'Mass', value: '2.307 × 10²¹ kg' },
      { label: 'Orbital Period', value: '4.518 days' },
      { label: 'Distance from Saturn', value: '527,070 km' },
      { label: 'Surface Temp', value: '-174°C' },
      { label: 'Notable', value: 'Second largest Saturnian moon' },
      { label: 'Composition', value: '75% water ice · 25% rock' },
    ],
  },
  Titan: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '5,150 km' },
      { label: 'Orbital Period', value: '15.95 days' },
      { label: 'Atmosphere', value: 'Thick N₂/CH₄ haze' },
    ],
    details: [
      { label: 'Classification', value: 'Largest Saturnian Moon' },
      { label: 'Diameter', value: '5,150 km (larger than Mercury)' },
      { label: 'Mass', value: '1.345 × 10²³ kg' },
      { label: 'Orbital Period', value: '15.945 days' },
      { label: 'Distance from Saturn', value: '1,221,870 km' },
      { label: 'Surface Temp', value: '-179°C' },
      { label: 'Atmosphere', value: 'Dense N₂ + CH₄; 1.5× Earth surface pressure' },
      { label: 'Notable', value: 'Liquid methane seas; only known ocean moon' },
    ],
  },
  Iapetus: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,469 km' },
      { label: 'Orbital Period', value: '79.33 days' },
      { label: 'Surface', value: 'Stark dark/light hemispheres' },
    ],
    details: [
      { label: 'Classification', value: 'Saturnian Moon' },
      { label: 'Diameter', value: '1,469 km' },
      { label: 'Mass', value: '1.806 × 10²¹ kg' },
      { label: 'Orbital Period', value: '79.33 days' },
      { label: 'Distance from Saturn', value: '3,560,840 km' },
      { label: 'Surface Temp', value: '-143°C (dark) / -173°C (bright)' },
      { label: 'Notable', value: 'Leading side coal-black; trailing side snow-white' },
      { label: 'Quirk', value: 'Equatorial ridge forms a 20 km mountain belt' },
    ],
  },
  Uranus: {
    type: 'Ice Giant',
    tooltip: [
      { label: 'Diameter', value: '50,724 km' },
      { label: 'Orbital Period', value: '84.01 years' },
      { label: 'Avg Temp', value: '-197°C' },
    ],
    details: [
      { label: 'Classification', value: 'Ice Giant' },
      { label: 'Diameter', value: '50,724 km' },
      { label: 'Mass', value: '8.681 × 10²⁵ kg' },
      { label: 'Distance from Sun', value: '19.18 AU' },
      { label: 'Orbital Period', value: '84.01 years' },
      { label: 'Rotation Period', value: '17h 14m (retrograde)' },
      { label: 'Avg Temperature', value: '-197°C' },
      { label: 'Known Moons', value: '28' },
    ],
  },
  Neptune: {
    type: 'Ice Giant',
    tooltip: [
      { label: 'Diameter', value: '49,244 km' },
      { label: 'Orbital Period', value: '164.8 years' },
      { label: 'Avg Temp', value: '-201°C' },
    ],
    details: [
      { label: 'Classification', value: 'Ice Giant' },
      { label: 'Diameter', value: '49,244 km' },
      { label: 'Mass', value: '1.024 × 10²⁶ kg' },
      { label: 'Distance from Sun', value: '30.07 AU' },
      { label: 'Orbital Period', value: '164.8 years' },
      { label: 'Rotation Period', value: '16h 6m' },
      { label: 'Avg Temperature', value: '-201°C' },
      { label: 'Known Moons', value: '16' },
    ],
  },

  // ── 55 Cancri (Copernicus) system ──
  '55 Cancri': {
    type: 'G8V Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '5,196 K' },
      { label: 'Distance',     value: '12.34 ly' },
      { label: 'Luminosity',   value: '0.582 L☉' },
    ],
    details: [
      { label: 'Classification', value: 'G8V Main Sequence' },
      { label: 'Mass',           value: '0.905 M☉' },
      { label: 'Radius',         value: '0.943 R☉' },
      { label: 'Surface Temp',   value: '5,196 K' },
      { label: 'Luminosity',     value: '0.582 L☉' },
      { label: 'Known Planets',  value: '5 (diverse types)' },
      { label: 'Age',            value: '~10.2 billion yrs' },
      { label: 'Distance',       value: '12.34 light-years' },
    ],
  },
  '55 Cnc e': {
    type: 'Ultra-hot Super-Earth (Lava World)',
    tooltip: [
      { label: 'Radius',   value: '1.875 R⊕' },
      { label: 'Period',   value: '0.737 days' },
      { label: 'Eq. Temp', value: '~1,953 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Earth / Lava World' },
      { label: 'Nickname',        value: 'Janssen' },
      { label: 'Radius',          value: '1.875 R⊕' },
      { label: 'Mass',            value: '7.99 M⊕' },
      { label: 'Orbital Period',  value: '0.7365 days' },
      { label: 'Semi-major Axis', value: '0.01544 AU' },
      { label: 'Eq. Temperature', value: '~1,953 K (~1,680°C)' },
      { label: 'Surface',         value: 'Likely molten ocean of lava' },
    ],
  },
  '55 Cnc b': {
    type: 'Hot Jupiter',
    tooltip: [
      { label: 'Mass',     value: '0.831 M♃' },
      { label: 'Period',   value: '14.65 days' },
      { label: 'Eq. Temp', value: '~720 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Hot Jupiter' },
      { label: 'Nickname',        value: 'Galileo' },
      { label: 'Mass',            value: '0.831 M♃ (264 M⊕)' },
      { label: 'Radius (est.)',   value: '~13 R⊕' },
      { label: 'Orbital Period',  value: '14.65 days' },
      { label: 'Semi-major Axis', value: '0.1134 AU' },
      { label: 'Eq. Temperature', value: '~720 K (447°C)' },
      { label: 'Detection',       value: 'Radial velocity' },
    ],
  },
  '55 Cnc c': {
    type: 'Warm Neptune-like Planet',
    tooltip: [
      { label: 'Mass',     value: '0.171 M♃' },
      { label: 'Period',   value: '44.34 days' },
      { label: 'Eq. Temp', value: '~498 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Warm Neptune / Sub-Saturn' },
      { label: 'Nickname',        value: 'Brahe' },
      { label: 'Mass',            value: '0.171 M♃ (54.3 M⊕)' },
      { label: 'Radius (est.)',   value: '~7 R⊕' },
      { label: 'Orbital Period',  value: '44.34 days' },
      { label: 'Semi-major Axis', value: '0.2373 AU' },
      { label: 'Eq. Temperature', value: '~498 K (225°C)' },
      { label: 'Detection',       value: 'Radial velocity' },
    ],
  },
  '55 Cnc f': {
    type: 'Sub-Jupiter (Habitable Zone)',
    tooltip: [
      { label: 'Mass',     value: '0.44 M♃' },
      { label: 'Period',   value: '259.7 days' },
      { label: 'Eq. Temp', value: '~274 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Sub-Jupiter / Habitable Zone' },
      { label: 'Nickname',        value: 'Lipperhey' },
      { label: 'Mass',            value: '0.44 M♃ (140 M⊕)' },
      { label: 'Radius (est.)',   value: '~9 R⊕' },
      { label: 'Orbital Period',  value: '259.7 days' },
      { label: 'Semi-major Axis', value: '0.781 AU' },
      { label: 'Eq. Temperature', value: '~274 K (1°C)' },
      { label: 'Habitable Zone',  value: 'Yes — gas giant in HZ' },
    ],
  },
  '55 Cnc d': {
    type: 'Outer Super-Jupiter',
    tooltip: [
      { label: 'Mass',     value: '3.84 M♃' },
      { label: 'Period',   value: '14.29 years' },
      { label: 'Eq. Temp', value: '~101 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter (Jupiter analogue)' },
      { label: 'Nickname',        value: 'Harriot' },
      { label: 'Mass',            value: '3.84 M♃ (1,221 M⊕)' },
      { label: 'Radius (est.)',   value: '~14 R⊕' },
      { label: 'Orbital Period',  value: '5,218 days (14.29 yrs)' },
      { label: 'Semi-major Axis', value: '5.74 AU' },
      { label: 'Eq. Temperature', value: '~101 K (-172°C)' },
      { label: 'Analogue',        value: 'Jupiter-analogue in outer system' },
    ],
  },

  // ── HR 8799 system ──
  'HR 8799': {
    type: 'A5V Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '~7,430 K' },
      { label: 'Distance',     value: '129 ly' },
      { label: 'Age',          value: '~30–60 Myr' },
    ],
    details: [
      { label: 'Classification', value: 'A5V Main Sequence' },
      { label: 'Mass',           value: '1.47 M☉' },
      { label: 'Radius',         value: '1.44 R☉' },
      { label: 'Surface Temp',   value: '~7,430 K' },
      { label: 'Luminosity',     value: '4.92 L☉' },
      { label: 'Known Planets',  value: '4 (directly imaged)' },
      { label: 'Age',            value: '~30–60 million yrs' },
      { label: 'Distance',       value: '129 light-years' },
    ],
  },
  'HR 8799e': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',       value: '~9 M♃' },
      { label: 'Period',     value: '~45 years' },
      { label: 'Atm. Temp',  value: '~1,150 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~9 M♃' },
      { label: 'Semi-major Axis', value: '~14.5 AU' },
      { label: 'Orbital Period',  value: '~45 years' },
      { label: 'Atm. Temperature', value: '~1,150 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2010)' },
      { label: 'Orbital Resonance', value: '1:2:4:8 with b, c, d' },
      { label: 'Status',          value: 'Innermost imaged planet' },
    ],
  },
  'HR 8799d': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~9 M♃' },
      { label: 'Period',    value: '~100 years' },
      { label: 'Atm. Temp', value: '~1,090 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~9 M♃' },
      { label: 'Semi-major Axis', value: '~24 AU' },
      { label: 'Orbital Period',  value: '~100 years' },
      { label: 'Atm. Temperature', value: '~1,090 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Orbital Resonance', value: 'Near 1:2 with HR 8799e' },
      { label: 'Atmosphere',      value: 'Thick clouds, methane detected' },
    ],
  },
  'HR 8799c': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~7 M♃' },
      { label: 'Period',    value: '~190 years' },
      { label: 'Atm. Temp', value: '~1,090 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~7 M♃' },
      { label: 'Semi-major Axis', value: '~38 AU' },
      { label: 'Orbital Period',  value: '~190 years' },
      { label: 'Atm. Temperature', value: '~1,090 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Atmosphere',      value: 'CO₂, H₂O, CO detected' },
      { label: 'Orbital Resonance', value: 'Near 1:2 with HR 8799d' },
    ],
  },
  'HR 8799b': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~6 M♃' },
      { label: 'Period',    value: '~460 years' },
      { label: 'Atm. Temp', value: '~1,000 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~6 M♃' },
      { label: 'Semi-major Axis', value: '~68 AU' },
      { label: 'Orbital Period',  value: '~460 years' },
      { label: 'Atm. Temperature', value: '~1,000 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Atmosphere',      value: 'CH₄ absorption detected' },
      { label: 'Status',          value: 'Outermost imaged planet' },
    ],
  },

  // ── Kepler-16 system ──
  'Kepler-16A': {
    type: 'K-Type Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '4,450 K' },
      { label: 'Mass',         value: '0.69 M☉' },
      { label: 'Distance',     value: '245 ly' },
    ],
    details: [
      { label: 'Classification',  value: 'K-type main sequence (K7V)' },
      { label: 'Mass',            value: '0.6897 M☉' },
      { label: 'Radius',          value: '0.6489 R☉' },
      { label: 'Surface Temp',    value: '4,450 K' },
      { label: 'Luminosity',      value: '0.139 L☉' },
      { label: 'Binary Period',   value: '41.08 days (with Kepler-16B)' },
      { label: 'Distance',        value: '~245 light-years' },
      { label: 'Constellation',   value: 'Cygnus' },
    ],
  },
  'Kepler-16B': {
    type: 'M-Type Red Dwarf',
    tooltip: [
      { label: 'Surface Temp', value: '3,311 K' },
      { label: 'Mass',         value: '0.20 M☉' },
      { label: 'Type',         value: 'Red dwarf companion' },
    ],
    details: [
      { label: 'Classification',  value: 'M-type red dwarf' },
      { label: 'Mass',            value: '0.2036 M☉' },
      { label: 'Radius',          value: '0.2265 R☉' },
      { label: 'Surface Temp',    value: '3,311 K' },
      { label: 'Luminosity',      value: '0.0072 L☉' },
      { label: 'Binary Period',   value: '41.08 days (with Kepler-16A)' },
      { label: 'Separation',      value: '~0.224 AU from Kepler-16A' },
      { label: 'Status',          value: 'Smaller of the binary pair' },
    ],
  },
  'Kepler-16b': {
    type: 'Circumbinary Gas Giant',
    tooltip: [
      { label: 'Mass',    value: '0.333 M♃' },
      { label: 'Period',  value: '228.8 days' },
      { label: 'Temp',    value: '~170 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Circumbinary gas giant' },
      { label: 'Mass',            value: '0.333 M♃ (105 M⊕)' },
      { label: 'Radius',          value: '0.7538 R♃ (~8.5 R⊕)' },
      { label: 'Orbital Period',  value: '228.776 days' },
      { label: 'Semi-major Axis', value: '0.7048 AU (from barycenter)' },
      { label: 'Eq. Temperature', value: '~170 K (−103°C)' },
      { label: 'Discovery',       value: '2011, Kepler transit photometry' },
      { label: 'Notable',         value: 'First confirmed circumbinary planet' },
    ],
  },

  // ── T Coronae Borealis (cataclysmic variable) ──
  'Red Giant': {
    type: 'M4 III Red Giant',
    tooltip: [
      { label: 'Spectral Type', value: 'M4 III' },
      { label: 'Radius',        value: '~75 R☉' },
      { label: 'Surface Temp',  value: '~3,500 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Red Giant (M4 III)' },
      { label: 'Mass',            value: '~0.7 M☉' },
      { label: 'Radius',          value: '~75 R☉ (fills Roche lobe)' },
      { label: 'Surface Temp',    value: '~3,500 K' },
      { label: 'Luminosity',      value: '~600 L☉' },
      { label: 'Role',            value: 'Donor star — mass transferred to WD' },
      { label: 'Roche Lobe',      value: 'Overflowing through inner Lagrange point (L1)' },
      { label: 'System',          value: 'T Coronae Borealis' },
    ],
  },
  'White Dwarf': {
    type: 'CO White Dwarf',
    tooltip: [
      { label: 'Mass',         value: '~1.2 M☉' },
      { label: 'Radius',       value: '~0.008 R☉' },
      { label: 'Surface Temp', value: '~100,000 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Carbon-Oxygen White Dwarf' },
      { label: 'Mass',            value: '~1.2 M☉ (near Chandrasekhar limit)' },
      { label: 'Radius',          value: '~5,500 km (~0.008 R☉)' },
      { label: 'Surface Temp',    value: '~100,000 K' },
      { label: 'Surface Gravity', value: '~300,000× Earth' },
      { label: 'Accretion Rate',  value: '~10⁻⁸ M☉/yr' },
      { label: 'Accretion Disk',  value: 'Hot inner disk ~10⁶ K' },
      { label: 'Nova Eruptions',  value: 'Recurrent — 1866 & 1946 observed' },
    ],
  },

  // ── Black Hole ──
  'Black Hole': {
    type: 'Supermassive Black Hole',
    tooltip: [
      { label: 'Shadow Radius', value: '~5.2 R_s' },
      { label: 'Disk Temp',     value: '~10⁷ K (inner)' },
      { label: 'Jets',          value: 'Relativistic bipolar' },
    ],
    details: [
      { label: 'Classification',  value: 'Supermassive Black Hole' },
      { label: 'Event Horizon',   value: 'Schwarzschild radius (R_s = 2GM/c²)' },
      { label: 'Photon Sphere',   value: '1.5 R_s — unstable circular photon orbits' },
      { label: 'ISCO',            value: '3 R_s — innermost stable circular orbit' },
      { label: 'Accretion Disk',  value: 'Relativistic — Doppler beaming visible' },
      { label: 'Disk Temp',       value: '~10⁷ K at inner edge' },
      { label: 'Jets',            value: 'Bipolar — near-luminal plasma outflow' },
      { label: 'Lensing',         value: 'Gravitational — null geodesic deflection' },
    ],
  },

  // ── TRAPPIST-1 system ──
  'TRAPPIST-1': {
    type: 'Ultra-cool Red Dwarf (M8V)',
    tooltip: [
      { label: 'Surface Temp', value: '2,566 K' },
      { label: 'Radius',       value: '0.1192 R☉' },
      { label: 'Distance',     value: '39.46 ly' },
    ],
    details: [
      { label: 'Classification', value: 'M8V Red Dwarf' },
      { label: 'Mass',           value: '0.0898 M☉' },
      { label: 'Radius',         value: '0.1192 R☉' },
      { label: 'Surface Temp',   value: '2,566 K' },
      { label: 'Luminosity',     value: '0.000522 L☉' },
      { label: 'Known Planets',  value: '7 (all rocky)' },
      { label: 'Age',            value: '~7.6 billion yrs' },
      { label: 'Distance',       value: '39.46 light-years' },
    ],
  },
  'TRAPPIST-1b': {
    type: 'Ultra-hot Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '1.116 R⊕' },
      { label: 'Period',  value: '1.511 days' },
      { label: 'Eq. Temp', value: '~400 K (127°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Ultra-hot Rocky' },
      { label: 'Radius',         value: '1.116 R⊕' },
      { label: 'Mass',           value: '1.374 M⊕' },
      { label: 'Orbital Period', value: '1.511 days' },
      { label: 'Semi-major Axis', value: '0.01154 AU' },
      { label: 'Eq. Temperature', value: '~400 K (127°C)' },
      { label: 'Tidal Locking',  value: 'Very likely' },
      { label: 'Habitable Zone', value: 'No — too hot' },
    ],
  },
  'TRAPPIST-1c': {
    type: 'Hot Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '1.097 R⊕' },
      { label: 'Period',  value: '2.422 days' },
      { label: 'Eq. Temp', value: '~342 K (69°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Hot Rocky' },
      { label: 'Radius',         value: '1.097 R⊕' },
      { label: 'Mass',           value: '1.308 M⊕' },
      { label: 'Orbital Period', value: '2.422 days' },
      { label: 'Semi-major Axis', value: '0.01580 AU' },
      { label: 'Eq. Temperature', value: '~342 K (69°C)' },
      { label: 'Tidal Locking',  value: 'Very likely' },
      { label: 'Habitable Zone', value: 'No — too hot' },
    ],
  },
  'TRAPPIST-1d': {
    type: 'Warm Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '0.788 R⊕' },
      { label: 'Period',  value: '4.050 days' },
      { label: 'Eq. Temp', value: '~288 K (15°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Warm Rocky' },
      { label: 'Radius',         value: '0.788 R⊕' },
      { label: 'Mass',           value: '0.388 M⊕' },
      { label: 'Orbital Period', value: '4.050 days' },
      { label: 'Semi-major Axis', value: '0.02227 AU' },
      { label: 'Eq. Temperature', value: '~288 K (15°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Inner edge (optimistic)' },
    ],
  },
  'TRAPPIST-1e': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '0.920 R⊕' },
      { label: 'Period',  value: '6.101 days' },
      { label: 'Eq. Temp', value: '~251 K (-22°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Habitable Zone Rocky' },
      { label: 'Radius',         value: '0.920 R⊕' },
      { label: 'Mass',           value: '0.692 M⊕' },
      { label: 'Orbital Period', value: '6.101 days' },
      { label: 'Semi-major Axis', value: '0.02925 AU' },
      { label: 'Eq. Temperature', value: '~251 K (-22°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — most Earth-like' },
    ],
  },
  'TRAPPIST-1f': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '1.045 R⊕' },
      { label: 'Period',  value: '9.207 days' },
      { label: 'Eq. Temp', value: '~219 K (-54°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Habitable Zone Rocky' },
      { label: 'Radius',         value: '1.045 R⊕' },
      { label: 'Mass',           value: '1.039 M⊕' },
      { label: 'Orbital Period', value: '9.207 days' },
      { label: 'Semi-major Axis', value: '0.03849 AU' },
      { label: 'Eq. Temperature', value: '~219 K (-54°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — possibly icy' },
    ],
  },
  'TRAPPIST-1g': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '1.129 R⊕' },
      { label: 'Period',  value: '12.353 days' },
      { label: 'Eq. Temp', value: '~199 K (-74°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Outer Habitable Zone Rocky' },
      { label: 'Radius',         value: '1.129 R⊕' },
      { label: 'Mass',           value: '1.321 M⊕' },
      { label: 'Orbital Period', value: '12.353 days' },
      { label: 'Semi-major Axis', value: '0.04683 AU' },
      { label: 'Eq. Temperature', value: '~199 K (-74°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — outer edge' },
    ],
  },
  'TRAPPIST-1h': {
    type: 'Icy Outer Planet',
    tooltip: [
      { label: 'Radius',  value: '0.755 R⊕' },
      { label: 'Period',  value: '18.767 days' },
      { label: 'Eq. Temp', value: '~173 K (-100°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Cold Rocky / Icy' },
      { label: 'Radius',         value: '0.755 R⊕' },
      { label: 'Mass',           value: '0.326 M⊕' },
      { label: 'Orbital Period', value: '18.767 days' },
      { label: 'Semi-major Axis', value: '0.06189 AU' },
      { label: 'Eq. Temperature', value: '~173 K (-100°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'No — too cold' },
    ],
  },
};

// Generate satellite data dynamically
for (let i = 1; i <= 5; i++) {
  const alt = (350 + i * 120).toLocaleString();
  const period = (92 + i * 3);
  const inc = [51.6, 98.2, 35.0, 74.1, 20.5][i - 1];
  OBJECT_DATA[`SAT-0${i}`] = {
    type: 'Artificial Satellite',
    tooltip: [
      { label: 'Altitude', value: `${alt} km` },
      { label: 'Orbital Period', value: `${period} min` },
      { label: 'Inclination', value: `${inc}°` },
    ],
    details: [
      { label: 'Classification', value: 'Artificial Satellite' },
      { label: 'Altitude', value: `${alt} km` },
      { label: 'Orbital Period', value: `${period} min` },
      { label: 'Inclination', value: `${inc}°` },
      { label: 'Velocity', value: `${(7.8 - i * 0.1).toFixed(1)} km/s` },
      { label: 'Status', value: 'Operational' },
    ],
  };
}
