// Stats for every named object
// tooltip: 3 quick stats shown on hover
// details: full list shown in the focus panel

export const OBJECT_DATA = {
  'Station 4': {
    type: 'Multi-Ring Orbital Station',
    tooltip: [
      { label: 'Rings',    value: '5 uniform' },
      { label: 'Diameter', value: '~880 m (ring)' },
      { label: 'Rotation', value: '~1.5 RPM' },
    ],
    details: [
      { label: 'Classification',  value: 'Multi-ring rotating station' },
      { label: 'Ring Count',       value: '5 identical levels' },
      { label: 'Ring Diameter',    value: '~880 m' },
      { label: 'Hub Height',       value: '~715 m' },
      { label: 'Spoke Corridors',  value: '8 per ring (40 total)' },
      { label: 'Rotation Rate',    value: '~1.5 RPM' },
      { label: 'Gravity (rim)',    value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',      value: '0 g (microgravity)' },
      { label: 'Crew Capacity',    value: 'Est. 2,000–5,000' },
      { label: 'Design',           value: 'Von Braun multi-wheel' },
    ],
  },

  'Station 3': {
    type: 'Advanced Orbital Colony',
    tooltip: [
      { label: 'Era',        value: 'c. 2230' },
      { label: 'Ring Levels', value: '5 (10 rings)' },
      { label: 'Crew',       value: '~10,000' },
    ],
    details: [
      { label: 'Classification',   value: 'Multi-ring orbital colony' },
      { label: 'Era',              value: 'c. 2230' },
      { label: 'Ring Levels',      value: '5 dual-ring levels' },
      { label: 'Max Ring Diameter', value: '~1,300 m (central level)' },
      { label: 'Spire Height',     value: '~760 m' },
      { label: 'Crew Capacity',    value: 'Est. 10,000' },
      { label: 'Gravity (rim)',    value: '~1 g (centrifugal)' },
      { label: 'Ring Rotation',    value: 'Counter-rotating pairs' },
      { label: 'Accelerator Ring', value: '~1,500 m diameter' },
      { label: 'Facilities',       value: 'Hangars, ag domes, labs' },
    ],
  },

  'Station 2': {
    type: 'Modular Orbital Station',
    tooltip: [
      { label: 'Orbit',       value: 'Low Earth Orbit' },
      { label: 'Ring Modules', value: '16 per ring' },
      { label: 'Rotation',    value: '~2 RPM' },
    ],
    details: [
      { label: 'Classification', value: 'Modular ring station' },
      { label: 'Ring Diameter',  value: '~274 m' },
      { label: 'Ring Modules',   value: '16 cylindrical segments' },
      { label: 'Rotation Rate',  value: '~2 RPM' },
      { label: 'Gravity (rim)',  value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',    value: '0 g (microgravity)' },
      { label: 'Crew Capacity',  value: 'Est. several hundred' },
      { label: 'Design',         value: 'Modular construction concept' },
    ],
  },

  'Station 1': {
    type: 'Orbital Space Station',
    tooltip: [
      { label: 'Orbit',    value: 'Low Earth Orbit' },
      { label: 'Diameter', value: '~274 m (ring)' },
      { label: 'Rotation', value: '~2 RPM' },
    ],
    details: [
      { label: 'Classification', value: 'Rotating ring station' },
      { label: 'Ring Diameter',  value: '~274 m' },
      { label: 'Rotation Rate',  value: '~2 RPM' },
      { label: 'Gravity (rim)',  value: '~1 g (centrifugal)' },
      { label: 'Hub Gravity',    value: '0 g (microgravity)' },
      { label: 'Crew Capacity',  value: 'Est. several hundred' },
      { label: 'Orbit Altitude', value: '~550 km' },
      { label: 'Design',         value: 'von Braun wheel concept' },
    ],
  },

  Sun: {
    type: 'G-Type Star',
    tooltip: [
      { label: 'Surface Temp', value: '5,778 K' },
      { label: 'Diameter', value: '1,392,700 km' },
      { label: 'Age', value: '4.6 Billion yrs' },
    ],
    details: [
      { label: 'Classification', value: 'G-type Main Sequence' },
      { label: 'Diameter', value: '1,392,700 km' },
      { label: 'Mass', value: '1.989 × 10³⁰ kg' },
      { label: 'Surface Temp', value: '5,778 K' },
      { label: 'Core Temp', value: '~15,000,000 K' },
      { label: 'Luminosity', value: '3.828 × 10²⁶ W' },
      { label: 'Composition', value: '73% H · 25% He' },
      { label: 'Age', value: '4.603 billion years' },
    ],
  },
  Mercury: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '4,879 km' },
      { label: 'Orbital Period', value: '88 days' },
      { label: 'Surface Temp', value: '-180 to 430°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '4,879 km' },
      { label: 'Mass', value: '3.285 × 10²³ kg' },
      { label: 'Distance from Sun', value: '0.39 AU' },
      { label: 'Orbital Period', value: '88 days' },
      { label: 'Rotation Period', value: '58.6 days' },
      { label: 'Surface Temp', value: '-180°C to 430°C' },
      { label: 'Known Moons', value: '0' },
    ],
  },
  Venus: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '12,104 km' },
      { label: 'Orbital Period', value: '225 days' },
      { label: 'Surface Temp', value: '465°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '12,104 km' },
      { label: 'Mass', value: '4.867 × 10²⁴ kg' },
      { label: 'Distance from Sun', value: '0.72 AU' },
      { label: 'Orbital Period', value: '225 days' },
      { label: 'Rotation Period', value: '243 days (retrograde)' },
      { label: 'Surface Temp', value: '465°C (avg)' },
      { label: 'Known Moons', value: '0' },
    ],
  },
  Earth: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '12,742 km' },
      { label: 'Orbital Period', value: '365.25 days' },
      { label: 'Surface Temp', value: '-88 to 58°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '12,742 km' },
      { label: 'Mass', value: '5.972 × 10²⁴ kg' },
      { label: 'Distance from Sun', value: '1.00 AU' },
      { label: 'Orbital Period', value: '365.25 days' },
      { label: 'Rotation Period', value: '23h 56m' },
      { label: 'Surface Temp', value: '-88°C to 58°C' },
      { label: 'Known Moons', value: '1' },
    ],
  },
  Moon: {
    type: 'Natural Satellite',
    tooltip: [
      { label: 'Diameter', value: '3,474 km' },
      { label: 'Orbital Period', value: '27.3 days' },
      { label: 'Distance', value: '384,400 km' },
    ],
    details: [
      { label: 'Classification', value: 'Natural Satellite' },
      { label: 'Diameter', value: '3,474 km' },
      { label: 'Mass', value: '7.342 × 10²² kg' },
      { label: 'Distance from Earth', value: '384,400 km' },
      { label: 'Orbital Period', value: '27.3 days' },
      { label: 'Rotation Period', value: '27.3 days (tidally locked)' },
      { label: 'Surface Temp', value: '-173°C to 127°C' },
      { label: 'Surface Gravity', value: '1.62 m/s²' },
    ],
  },
  Mars: {
    type: 'Terrestrial Planet',
    tooltip: [
      { label: 'Diameter', value: '6,779 km' },
      { label: 'Orbital Period', value: '687 days' },
      { label: 'Surface Temp', value: '-140 to 20°C' },
    ],
    details: [
      { label: 'Classification', value: 'Terrestrial Planet' },
      { label: 'Diameter', value: '6,779 km' },
      { label: 'Mass', value: '6.39 × 10²³ kg' },
      { label: 'Distance from Sun', value: '1.52 AU' },
      { label: 'Orbital Period', value: '687 days' },
      { label: 'Rotation Period', value: '24h 37m' },
      { label: 'Surface Temp', value: '-140°C to 20°C' },
      { label: 'Known Moons', value: '2' },
    ],
  },
  Phobos: {
    type: 'Martian Moon',
    tooltip: [
      { label: 'Diameter', value: '~22 km' },
      { label: 'Orbital Period', value: '7.65 hours' },
      { label: 'Notable', value: 'Faster than Mars rotates' },
    ],
    details: [
      { label: 'Classification', value: 'Inner Martian Moon' },
      { label: 'Dimensions', value: '27 × 22 × 18 km' },
      { label: 'Mass', value: '1.066 × 10¹⁶ kg' },
      { label: 'Orbital Period', value: '7.651 hours' },
      { label: 'Distance from Mars', value: '9,376 km' },
      { label: 'Surface Temp', value: '-40°C (avg)' },
      { label: 'Notable', value: 'Orbits faster than Mars spins — rises in the west' },
      { label: 'Fate', value: 'Spiraling inward; will break apart in ~30–50 Myr' },
    ],
  },
  Deimos: {
    type: 'Martian Moon',
    tooltip: [
      { label: 'Diameter', value: '~12 km' },
      { label: 'Orbital Period', value: '1.263 days' },
      { label: 'Origin', value: 'Captured asteroid' },
    ],
    details: [
      { label: 'Classification', value: 'Outer Martian Moon' },
      { label: 'Dimensions', value: '15 × 12 × 11 km' },
      { label: 'Mass', value: '1.476 × 10¹⁵ kg' },
      { label: 'Orbital Period', value: '1.263 days' },
      { label: 'Distance from Mars', value: '23,460 km' },
      { label: 'Surface Temp', value: '-40°C (avg)' },
      { label: 'Origin', value: 'Likely captured C-type asteroid' },
      { label: 'Notable', value: 'Smooth, heavily cratered, very low gravity' },
    ],
  },
  Jupiter: {
    type: 'Gas Giant',
    tooltip: [
      { label: 'Diameter', value: '139,820 km' },
      { label: 'Orbital Period', value: '11.86 years' },
      { label: 'Known Moons', value: '95' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant' },
      { label: 'Diameter', value: '139,820 km' },
      { label: 'Mass', value: '1.898 × 10²⁷ kg' },
      { label: 'Distance from Sun', value: '5.20 AU' },
      { label: 'Orbital Period', value: '11.86 years' },
      { label: 'Rotation Period', value: '9h 56m' },
      { label: 'Avg Temperature', value: '-108°C' },
      { label: 'Known Moons', value: '95' },
    ],
  },
  Io: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '3,643 km' },
      { label: 'Orbital Period', value: '1.77 days' },
      { label: 'Surface Temp', value: '-130°C avg' },
    ],
    details: [
      { label: 'Classification', value: 'Volcanic Galilean Moon' },
      { label: 'Diameter', value: '3,643 km' },
      { label: 'Mass', value: '8.932 × 10²² kg' },
      { label: 'Orbital Period', value: '1.769 days' },
      { label: 'Distance from Jupiter', value: '421,800 km' },
      { label: 'Surface Temp', value: '-130°C (avg) / 1,600°C (lava)' },
      { label: 'Notable', value: 'Most volcanically active body in Solar System' },
      { label: 'Tidal heating by', value: 'Jupiter + Europa + Ganymede resonance' },
    ],
  },
  Europa: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '3,122 km' },
      { label: 'Orbital Period', value: '3.55 days' },
      { label: 'Ocean Depth', value: '~100 km' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Galilean Moon' },
      { label: 'Diameter', value: '3,122 km' },
      { label: 'Mass', value: '4.800 × 10²² kg' },
      { label: 'Orbital Period', value: '3.551 days' },
      { label: 'Distance from Jupiter', value: '671,100 km' },
      { label: 'Surface Temp', value: '-160°C (avg)' },
      { label: 'Notable', value: 'Subsurface liquid water ocean ~100 km deep' },
      { label: 'Habitability', value: 'Prime candidate for extraterrestrial life' },
    ],
  },
  Ganymede: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '5,268 km' },
      { label: 'Orbital Period', value: '7.15 days' },
      { label: 'Notable', value: 'Largest moon in Solar System' },
    ],
    details: [
      { label: 'Classification', value: 'Galilean Moon' },
      { label: 'Diameter', value: '5,268 km' },
      { label: 'Mass', value: '1.482 × 10²³ kg' },
      { label: 'Orbital Period', value: '7.155 days' },
      { label: 'Distance from Jupiter', value: '1,070,400 km' },
      { label: 'Surface Temp', value: '-163°C (avg)' },
      { label: 'Notable', value: 'Largest moon in Solar System; larger than Mercury' },
      { label: 'Magnetosphere', value: 'Only moon with its own magnetic field' },
    ],
  },
  Callisto: {
    type: 'Jovian Moon',
    tooltip: [
      { label: 'Diameter', value: '4,821 km' },
      { label: 'Orbital Period', value: '16.7 days' },
      { label: 'Surface', value: 'Most cratered in Solar System' },
    ],
    details: [
      { label: 'Classification', value: 'Galilean Moon' },
      { label: 'Diameter', value: '4,821 km' },
      { label: 'Mass', value: '1.076 × 10²³ kg' },
      { label: 'Orbital Period', value: '16.69 days' },
      { label: 'Distance from Jupiter', value: '1,882,700 km' },
      { label: 'Surface Temp', value: '-139°C (avg)' },
      { label: 'Notable', value: 'Most heavily cratered object in Solar System' },
      { label: 'Interior', value: 'Possible subsurface ocean; geologically inactive' },
    ],
  },
  Saturn: {
    type: 'Gas Giant',
    tooltip: [
      { label: 'Diameter', value: '116,460 km' },
      { label: 'Orbital Period', value: '29.46 years' },
      { label: 'Known Moons', value: '146' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant' },
      { label: 'Diameter', value: '116,460 km' },
      { label: 'Mass', value: '5.683 × 10²⁶ kg' },
      { label: 'Distance from Sun', value: '9.58 AU' },
      { label: 'Orbital Period', value: '29.46 years' },
      { label: 'Rotation Period', value: '10h 33m' },
      { label: 'Avg Temperature', value: '-139°C' },
      { label: 'Known Moons', value: '146' },
    ],
  },
  Mimas: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '396 km' },
      { label: 'Orbital Period', value: '0.942 days' },
      { label: 'Notable', value: '"Death Star" crater' },
    ],
    details: [
      { label: 'Classification', value: 'Small Saturnian Moon' },
      { label: 'Diameter', value: '396 km' },
      { label: 'Mass', value: '3.749 × 10¹⁹ kg' },
      { label: 'Orbital Period', value: '0.942 days' },
      { label: 'Distance from Saturn', value: '185,540 km' },
      { label: 'Surface Temp', value: '-209°C' },
      { label: 'Notable', value: 'Herschel crater = 130 km across ("Death Star")' },
      { label: 'Quirk', value: 'Resonance with Tethys locks orbital period 1:2' },
    ],
  },
  Enceladus: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '504 km' },
      { label: 'Orbital Period', value: '1.37 days' },
      { label: 'Notable', value: 'Active water geysers' },
    ],
    details: [
      { label: 'Classification', value: 'Active Icy Moon' },
      { label: 'Diameter', value: '504 km' },
      { label: 'Mass', value: '1.080 × 10²⁰ kg' },
      { label: 'Orbital Period', value: '1.370 days' },
      { label: 'Distance from Saturn', value: '238,040 km' },
      { label: 'Surface Temp', value: '-201°C (avg)' },
      { label: 'Notable', value: 'Active geysers erupt liquid water into space' },
      { label: 'Habitability', value: 'Subsurface ocean; prime life candidate' },
    ],
  },
  Tethys: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,062 km' },
      { label: 'Orbital Period', value: '1.888 days' },
      { label: 'Composition', value: 'Nearly pure water ice' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,062 km' },
      { label: 'Mass', value: '6.175 × 10²⁰ kg' },
      { label: 'Orbital Period', value: '1.888 days' },
      { label: 'Distance from Saturn', value: '294,670 km' },
      { label: 'Surface Temp', value: '-187°C' },
      { label: 'Composition', value: 'Nearly pure water ice' },
      { label: 'Notable', value: 'Ithaca Chasma — vast canyon system' },
    ],
  },
  Dione: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,123 km' },
      { label: 'Orbital Period', value: '2.737 days' },
      { label: 'Surface', value: 'Ice cliffs and wispy streaks' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,123 km' },
      { label: 'Mass', value: '1.096 × 10²¹ kg' },
      { label: 'Orbital Period', value: '2.737 days' },
      { label: 'Distance from Saturn', value: '377,400 km' },
      { label: 'Surface Temp', value: '-186°C' },
      { label: 'Notable', value: 'Bright ice cliffs and wispy linear features' },
      { label: 'Resonance', value: 'Locked 1:2 with Enceladus' },
    ],
  },
  Rhea: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,528 km' },
      { label: 'Orbital Period', value: '4.518 days' },
      { label: 'Notable', value: 'Second largest moon of Saturn' },
    ],
    details: [
      { label: 'Classification', value: 'Icy Saturnian Moon' },
      { label: 'Diameter', value: '1,528 km' },
      { label: 'Mass', value: '2.307 × 10²¹ kg' },
      { label: 'Orbital Period', value: '4.518 days' },
      { label: 'Distance from Saturn', value: '527,070 km' },
      { label: 'Surface Temp', value: '-174°C' },
      { label: 'Notable', value: 'Second largest Saturnian moon' },
      { label: 'Composition', value: '75% water ice · 25% rock' },
    ],
  },
  Titan: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '5,150 km' },
      { label: 'Orbital Period', value: '15.95 days' },
      { label: 'Atmosphere', value: 'Thick N₂/CH₄ haze' },
    ],
    details: [
      { label: 'Classification', value: 'Largest Saturnian Moon' },
      { label: 'Diameter', value: '5,150 km (larger than Mercury)' },
      { label: 'Mass', value: '1.345 × 10²³ kg' },
      { label: 'Orbital Period', value: '15.945 days' },
      { label: 'Distance from Saturn', value: '1,221,870 km' },
      { label: 'Surface Temp', value: '-179°C' },
      { label: 'Atmosphere', value: 'Dense N₂ + CH₄; 1.5× Earth surface pressure' },
      { label: 'Notable', value: 'Liquid methane seas; only known ocean moon' },
    ],
  },
  Iapetus: {
    type: 'Saturnian Moon',
    tooltip: [
      { label: 'Diameter', value: '1,469 km' },
      { label: 'Orbital Period', value: '79.33 days' },
      { label: 'Surface', value: 'Stark dark/light hemispheres' },
    ],
    details: [
      { label: 'Classification', value: 'Saturnian Moon' },
      { label: 'Diameter', value: '1,469 km' },
      { label: 'Mass', value: '1.806 × 10²¹ kg' },
      { label: 'Orbital Period', value: '79.33 days' },
      { label: 'Distance from Saturn', value: '3,560,840 km' },
      { label: 'Surface Temp', value: '-143°C (dark) / -173°C (bright)' },
      { label: 'Notable', value: 'Leading side coal-black; trailing side snow-white' },
      { label: 'Quirk', value: 'Equatorial ridge forms a 20 km mountain belt' },
    ],
  },
  Uranus: {
    type: 'Ice Giant',
    tooltip: [
      { label: 'Diameter', value: '50,724 km' },
      { label: 'Orbital Period', value: '84.01 years' },
      { label: 'Avg Temp', value: '-197°C' },
    ],
    details: [
      { label: 'Classification', value: 'Ice Giant' },
      { label: 'Diameter', value: '50,724 km' },
      { label: 'Mass', value: '8.681 × 10²⁵ kg' },
      { label: 'Distance from Sun', value: '19.18 AU' },
      { label: 'Orbital Period', value: '84.01 years' },
      { label: 'Rotation Period', value: '17h 14m (retrograde)' },
      { label: 'Avg Temperature', value: '-197°C' },
      { label: 'Known Moons', value: '28' },
    ],
  },
  Neptune: {
    type: 'Ice Giant',
    tooltip: [
      { label: 'Diameter', value: '49,244 km' },
      { label: 'Orbital Period', value: '164.8 years' },
      { label: 'Avg Temp', value: '-201°C' },
    ],
    details: [
      { label: 'Classification', value: 'Ice Giant' },
      { label: 'Diameter', value: '49,244 km' },
      { label: 'Mass', value: '1.024 × 10²⁶ kg' },
      { label: 'Distance from Sun', value: '30.07 AU' },
      { label: 'Orbital Period', value: '164.8 years' },
      { label: 'Rotation Period', value: '16h 6m' },
      { label: 'Avg Temperature', value: '-201°C' },
      { label: 'Known Moons', value: '16' },
    ],
  },

  // ── 55 Cancri (Copernicus) system ──
  '55 Cancri': {
    type: 'G8V Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '5,196 K' },
      { label: 'Distance',     value: '12.34 ly' },
      { label: 'Luminosity',   value: '0.582 L☉' },
    ],
    details: [
      { label: 'Classification', value: 'G8V Main Sequence' },
      { label: 'Mass',           value: '0.905 M☉' },
      { label: 'Radius',         value: '0.943 R☉' },
      { label: 'Surface Temp',   value: '5,196 K' },
      { label: 'Luminosity',     value: '0.582 L☉' },
      { label: 'Known Planets',  value: '5 (diverse types)' },
      { label: 'Age',            value: '~10.2 billion yrs' },
      { label: 'Distance',       value: '12.34 light-years' },
    ],
  },
  '55 Cnc e': {
    type: 'Ultra-hot Super-Earth (Lava World)',
    tooltip: [
      { label: 'Radius',   value: '1.875 R⊕' },
      { label: 'Period',   value: '0.737 days' },
      { label: 'Eq. Temp', value: '~1,953 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Earth / Lava World' },
      { label: 'Nickname',        value: 'Janssen' },
      { label: 'Radius',          value: '1.875 R⊕' },
      { label: 'Mass',            value: '7.99 M⊕' },
      { label: 'Orbital Period',  value: '0.7365 days' },
      { label: 'Semi-major Axis', value: '0.01544 AU' },
      { label: 'Eq. Temperature', value: '~1,953 K (~1,680°C)' },
      { label: 'Surface',         value: 'Likely molten ocean of lava' },
    ],
  },
  '55 Cnc b': {
    type: 'Hot Jupiter',
    tooltip: [
      { label: 'Mass',     value: '0.831 M♃' },
      { label: 'Period',   value: '14.65 days' },
      { label: 'Eq. Temp', value: '~720 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Hot Jupiter' },
      { label: 'Nickname',        value: 'Galileo' },
      { label: 'Mass',            value: '0.831 M♃ (264 M⊕)' },
      { label: 'Radius (est.)',   value: '~13 R⊕' },
      { label: 'Orbital Period',  value: '14.65 days' },
      { label: 'Semi-major Axis', value: '0.1134 AU' },
      { label: 'Eq. Temperature', value: '~720 K (447°C)' },
      { label: 'Detection',       value: 'Radial velocity' },
    ],
  },
  '55 Cnc c': {
    type: 'Warm Neptune-like Planet',
    tooltip: [
      { label: 'Mass',     value: '0.171 M♃' },
      { label: 'Period',   value: '44.34 days' },
      { label: 'Eq. Temp', value: '~498 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Warm Neptune / Sub-Saturn' },
      { label: 'Nickname',        value: 'Brahe' },
      { label: 'Mass',            value: '0.171 M♃ (54.3 M⊕)' },
      { label: 'Radius (est.)',   value: '~7 R⊕' },
      { label: 'Orbital Period',  value: '44.34 days' },
      { label: 'Semi-major Axis', value: '0.2373 AU' },
      { label: 'Eq. Temperature', value: '~498 K (225°C)' },
      { label: 'Detection',       value: 'Radial velocity' },
    ],
  },
  '55 Cnc f': {
    type: 'Sub-Jupiter (Habitable Zone)',
    tooltip: [
      { label: 'Mass',     value: '0.44 M♃' },
      { label: 'Period',   value: '259.7 days' },
      { label: 'Eq. Temp', value: '~274 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Sub-Jupiter / Habitable Zone' },
      { label: 'Nickname',        value: 'Lipperhey' },
      { label: 'Mass',            value: '0.44 M♃ (140 M⊕)' },
      { label: 'Radius (est.)',   value: '~9 R⊕' },
      { label: 'Orbital Period',  value: '259.7 days' },
      { label: 'Semi-major Axis', value: '0.781 AU' },
      { label: 'Eq. Temperature', value: '~274 K (1°C)' },
      { label: 'Habitable Zone',  value: 'Yes — gas giant in HZ' },
    ],
  },
  '55 Cnc d': {
    type: 'Outer Super-Jupiter',
    tooltip: [
      { label: 'Mass',     value: '3.84 M♃' },
      { label: 'Period',   value: '14.29 years' },
      { label: 'Eq. Temp', value: '~101 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter (Jupiter analogue)' },
      { label: 'Nickname',        value: 'Harriot' },
      { label: 'Mass',            value: '3.84 M♃ (1,221 M⊕)' },
      { label: 'Radius (est.)',   value: '~14 R⊕' },
      { label: 'Orbital Period',  value: '5,218 days (14.29 yrs)' },
      { label: 'Semi-major Axis', value: '5.74 AU' },
      { label: 'Eq. Temperature', value: '~101 K (-172°C)' },
      { label: 'Analogue',        value: 'Jupiter-analogue in outer system' },
    ],
  },

  // ── HR 8799 system ──
  'HR 8799': {
    type: 'A5V Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '~7,430 K' },
      { label: 'Distance',     value: '129 ly' },
      { label: 'Age',          value: '~30–60 Myr' },
    ],
    details: [
      { label: 'Classification', value: 'A5V Main Sequence' },
      { label: 'Mass',           value: '1.47 M☉' },
      { label: 'Radius',         value: '1.44 R☉' },
      { label: 'Surface Temp',   value: '~7,430 K' },
      { label: 'Luminosity',     value: '4.92 L☉' },
      { label: 'Known Planets',  value: '4 (directly imaged)' },
      { label: 'Age',            value: '~30–60 million yrs' },
      { label: 'Distance',       value: '129 light-years' },
    ],
  },
  'HR 8799e': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',       value: '~9 M♃' },
      { label: 'Period',     value: '~45 years' },
      { label: 'Atm. Temp',  value: '~1,150 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~9 M♃' },
      { label: 'Semi-major Axis', value: '~14.5 AU' },
      { label: 'Orbital Period',  value: '~45 years' },
      { label: 'Atm. Temperature', value: '~1,150 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2010)' },
      { label: 'Orbital Resonance', value: '1:2:4:8 with b, c, d' },
      { label: 'Status',          value: 'Innermost imaged planet' },
    ],
  },
  'HR 8799d': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~9 M♃' },
      { label: 'Period',    value: '~100 years' },
      { label: 'Atm. Temp', value: '~1,090 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~9 M♃' },
      { label: 'Semi-major Axis', value: '~24 AU' },
      { label: 'Orbital Period',  value: '~100 years' },
      { label: 'Atm. Temperature', value: '~1,090 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Orbital Resonance', value: 'Near 1:2 with HR 8799e' },
      { label: 'Atmosphere',      value: 'Thick clouds, methane detected' },
    ],
  },
  'HR 8799c': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~7 M♃' },
      { label: 'Period',    value: '~190 years' },
      { label: 'Atm. Temp', value: '~1,090 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~7 M♃' },
      { label: 'Semi-major Axis', value: '~38 AU' },
      { label: 'Orbital Period',  value: '~190 years' },
      { label: 'Atm. Temperature', value: '~1,090 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Atmosphere',      value: 'CO₂, H₂O, CO detected' },
      { label: 'Orbital Resonance', value: 'Near 1:2 with HR 8799d' },
    ],
  },
  'HR 8799b': {
    type: 'Super-Jupiter (Directly Imaged)',
    tooltip: [
      { label: 'Mass',      value: '~6 M♃' },
      { label: 'Period',    value: '~460 years' },
      { label: 'Atm. Temp', value: '~1,000 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Super-Jupiter' },
      { label: 'Mass',            value: '~6 M♃' },
      { label: 'Semi-major Axis', value: '~68 AU' },
      { label: 'Orbital Period',  value: '~460 years' },
      { label: 'Atm. Temperature', value: '~1,000 K (self-luminous)' },
      { label: 'Detection',       value: 'Direct imaging (2008)' },
      { label: 'Atmosphere',      value: 'CH₄ absorption detected' },
      { label: 'Status',          value: 'Outermost imaged planet' },
    ],
  },

  // ── Kepler-16 system ──
  'Kepler-16A': {
    type: 'K-Type Main Sequence Star',
    tooltip: [
      { label: 'Surface Temp', value: '4,450 K' },
      { label: 'Mass',         value: '0.69 M☉' },
      { label: 'Distance',     value: '245 ly' },
    ],
    details: [
      { label: 'Classification',  value: 'K-type main sequence (K7V)' },
      { label: 'Mass',            value: '0.6897 M☉' },
      { label: 'Radius',          value: '0.6489 R☉' },
      { label: 'Surface Temp',    value: '4,450 K' },
      { label: 'Luminosity',      value: '0.139 L☉' },
      { label: 'Binary Period',   value: '41.08 days (with Kepler-16B)' },
      { label: 'Distance',        value: '~245 light-years' },
      { label: 'Constellation',   value: 'Cygnus' },
    ],
  },
  'Kepler-16B': {
    type: 'M-Type Red Dwarf',
    tooltip: [
      { label: 'Surface Temp', value: '3,311 K' },
      { label: 'Mass',         value: '0.20 M☉' },
      { label: 'Type',         value: 'Red dwarf companion' },
    ],
    details: [
      { label: 'Classification',  value: 'M-type red dwarf' },
      { label: 'Mass',            value: '0.2036 M☉' },
      { label: 'Radius',          value: '0.2265 R☉' },
      { label: 'Surface Temp',    value: '3,311 K' },
      { label: 'Luminosity',      value: '0.0072 L☉' },
      { label: 'Binary Period',   value: '41.08 days (with Kepler-16A)' },
      { label: 'Separation',      value: '~0.224 AU from Kepler-16A' },
      { label: 'Status',          value: 'Smaller of the binary pair' },
    ],
  },
  'Kepler-16b': {
    type: 'Circumbinary Gas Giant',
    tooltip: [
      { label: 'Mass',    value: '0.333 M♃' },
      { label: 'Period',  value: '228.8 days' },
      { label: 'Temp',    value: '~170 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Circumbinary gas giant' },
      { label: 'Mass',            value: '0.333 M♃ (105 M⊕)' },
      { label: 'Radius',          value: '0.7538 R♃ (~8.5 R⊕)' },
      { label: 'Orbital Period',  value: '228.776 days' },
      { label: 'Semi-major Axis', value: '0.7048 AU (from barycenter)' },
      { label: 'Eq. Temperature', value: '~170 K (−103°C)' },
      { label: 'Discovery',       value: '2011, Kepler transit photometry' },
      { label: 'Notable',         value: 'First confirmed circumbinary planet' },
    ],
  },

  // ── T Coronae Borealis (cataclysmic variable) ──
  'Red Giant': {
    type: 'M4 III Red Giant',
    tooltip: [
      { label: 'Spectral Type', value: 'M4 III' },
      { label: 'Radius',        value: '~75 R☉' },
      { label: 'Surface Temp',  value: '~3,500 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Red Giant (M4 III)' },
      { label: 'Mass',            value: '~0.7 M☉' },
      { label: 'Radius',          value: '~75 R☉ (fills Roche lobe)' },
      { label: 'Surface Temp',    value: '~3,500 K' },
      { label: 'Luminosity',      value: '~600 L☉' },
      { label: 'Role',            value: 'Donor star — mass transferred to WD' },
      { label: 'Roche Lobe',      value: 'Overflowing through inner Lagrange point (L1)' },
      { label: 'System',          value: 'T Coronae Borealis' },
    ],
  },
  'White Dwarf': {
    type: 'CO White Dwarf',
    tooltip: [
      { label: 'Mass',         value: '~1.2 M☉' },
      { label: 'Radius',       value: '~0.008 R☉' },
      { label: 'Surface Temp', value: '~100,000 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Carbon-Oxygen White Dwarf' },
      { label: 'Mass',            value: '~1.2 M☉ (near Chandrasekhar limit)' },
      { label: 'Radius',          value: '~5,500 km (~0.008 R☉)' },
      { label: 'Surface Temp',    value: '~100,000 K' },
      { label: 'Surface Gravity', value: '~300,000× Earth' },
      { label: 'Accretion Rate',  value: '~10⁻⁸ M☉/yr' },
      { label: 'Accretion Disk',  value: 'Hot inner disk ~10⁶ K' },
      { label: 'Nova Eruptions',  value: 'Recurrent — 1866 & 1946 observed' },
    ],
  },

  // ── Black Hole ──
  'Black Hole': {
    type: 'Supermassive Black Hole',
    tooltip: [
      { label: 'Shadow Radius', value: '~5.2 R_s' },
      { label: 'Disk Temp',     value: '~10⁷ K (inner)' },
      { label: 'Jets',          value: 'Relativistic bipolar' },
    ],
    details: [
      { label: 'Classification',  value: 'Supermassive Black Hole' },
      { label: 'Event Horizon',   value: 'Schwarzschild radius (R_s = 2GM/c²)' },
      { label: 'Photon Sphere',   value: '1.5 R_s — unstable circular photon orbits' },
      { label: 'ISCO',            value: '3 R_s — innermost stable circular orbit' },
      { label: 'Accretion Disk',  value: 'Relativistic — Doppler beaming visible' },
      { label: 'Disk Temp',       value: '~10⁷ K at inner edge' },
      { label: 'Jets',            value: 'Bipolar — near-luminal plasma outflow' },
      { label: 'Lensing',         value: 'Gravitational — null geodesic deflection' },
    ],
  },

  // ── TRAPPIST-1 system ──
  'TRAPPIST-1': {
    type: 'Ultra-cool Red Dwarf (M8V)',
    tooltip: [
      { label: 'Surface Temp', value: '2,566 K' },
      { label: 'Radius',       value: '0.1192 R☉' },
      { label: 'Distance',     value: '39.46 ly' },
    ],
    details: [
      { label: 'Classification', value: 'M8V Red Dwarf' },
      { label: 'Mass',           value: '0.0898 M☉' },
      { label: 'Radius',         value: '0.1192 R☉' },
      { label: 'Surface Temp',   value: '2,566 K' },
      { label: 'Luminosity',     value: '0.000522 L☉' },
      { label: 'Known Planets',  value: '7 (all rocky)' },
      { label: 'Age',            value: '~7.6 billion yrs' },
      { label: 'Distance',       value: '39.46 light-years' },
    ],
  },
  'TRAPPIST-1b': {
    type: 'Ultra-hot Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '1.116 R⊕' },
      { label: 'Period',  value: '1.511 days' },
      { label: 'Eq. Temp', value: '~400 K (127°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Ultra-hot Rocky' },
      { label: 'Radius',         value: '1.116 R⊕' },
      { label: 'Mass',           value: '1.374 M⊕' },
      { label: 'Orbital Period', value: '1.511 days' },
      { label: 'Semi-major Axis', value: '0.01154 AU' },
      { label: 'Eq. Temperature', value: '~400 K (127°C)' },
      { label: 'Tidal Locking',  value: 'Very likely' },
      { label: 'Habitable Zone', value: 'No — too hot' },
    ],
  },
  'TRAPPIST-1c': {
    type: 'Hot Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '1.097 R⊕' },
      { label: 'Period',  value: '2.422 days' },
      { label: 'Eq. Temp', value: '~342 K (69°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Hot Rocky' },
      { label: 'Radius',         value: '1.097 R⊕' },
      { label: 'Mass',           value: '1.308 M⊕' },
      { label: 'Orbital Period', value: '2.422 days' },
      { label: 'Semi-major Axis', value: '0.01580 AU' },
      { label: 'Eq. Temperature', value: '~342 K (69°C)' },
      { label: 'Tidal Locking',  value: 'Very likely' },
      { label: 'Habitable Zone', value: 'No — too hot' },
    ],
  },
  'TRAPPIST-1d': {
    type: 'Warm Rocky Planet',
    tooltip: [
      { label: 'Radius',  value: '0.788 R⊕' },
      { label: 'Period',  value: '4.050 days' },
      { label: 'Eq. Temp', value: '~288 K (15°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Warm Rocky' },
      { label: 'Radius',         value: '0.788 R⊕' },
      { label: 'Mass',           value: '0.388 M⊕' },
      { label: 'Orbital Period', value: '4.050 days' },
      { label: 'Semi-major Axis', value: '0.02227 AU' },
      { label: 'Eq. Temperature', value: '~288 K (15°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Inner edge (optimistic)' },
    ],
  },
  'TRAPPIST-1e': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '0.920 R⊕' },
      { label: 'Period',  value: '6.101 days' },
      { label: 'Eq. Temp', value: '~251 K (-22°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Habitable Zone Rocky' },
      { label: 'Radius',         value: '0.920 R⊕' },
      { label: 'Mass',           value: '0.692 M⊕' },
      { label: 'Orbital Period', value: '6.101 days' },
      { label: 'Semi-major Axis', value: '0.02925 AU' },
      { label: 'Eq. Temperature', value: '~251 K (-22°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — most Earth-like' },
    ],
  },
  'TRAPPIST-1f': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '1.045 R⊕' },
      { label: 'Period',  value: '9.207 days' },
      { label: 'Eq. Temp', value: '~219 K (-54°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Habitable Zone Rocky' },
      { label: 'Radius',         value: '1.045 R⊕' },
      { label: 'Mass',           value: '1.039 M⊕' },
      { label: 'Orbital Period', value: '9.207 days' },
      { label: 'Semi-major Axis', value: '0.03849 AU' },
      { label: 'Eq. Temperature', value: '~219 K (-54°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — possibly icy' },
    ],
  },
  'TRAPPIST-1g': {
    type: 'Habitable Zone Planet',
    tooltip: [
      { label: 'Radius',  value: '1.129 R⊕' },
      { label: 'Period',  value: '12.353 days' },
      { label: 'Eq. Temp', value: '~199 K (-74°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Outer Habitable Zone Rocky' },
      { label: 'Radius',         value: '1.129 R⊕' },
      { label: 'Mass',           value: '1.321 M⊕' },
      { label: 'Orbital Period', value: '12.353 days' },
      { label: 'Semi-major Axis', value: '0.04683 AU' },
      { label: 'Eq. Temperature', value: '~199 K (-74°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'Yes — outer edge' },
    ],
  },
  'TRAPPIST-1h': {
    type: 'Icy Outer Planet',
    tooltip: [
      { label: 'Radius',  value: '0.755 R⊕' },
      { label: 'Period',  value: '18.767 days' },
      { label: 'Eq. Temp', value: '~173 K (-100°C)' },
    ],
    details: [
      { label: 'Classification', value: 'Cold Rocky / Icy' },
      { label: 'Radius',         value: '0.755 R⊕' },
      { label: 'Mass',           value: '0.326 M⊕' },
      { label: 'Orbital Period', value: '18.767 days' },
      { label: 'Semi-major Axis', value: '0.06189 AU' },
      { label: 'Eq. Temperature', value: '~173 K (-100°C)' },
      { label: 'Tidal Locking',  value: 'Likely' },
      { label: 'Habitable Zone', value: 'No — too cold' },
    ],
  },

  // ── PSR B1257+12 (Lich) system ──
  'PSR B1257+12': {
    type: 'Millisecond Pulsar',
    tooltip: [
      { label: 'Spin Period', value: '6.22 ms' },
      { label: 'Distance',    value: '~2,300 ly' },
      { label: 'Known Planets', value: '3' },
    ],
    details: [
      { label: 'Classification', value: 'Millisecond Pulsar (recycled neutron star)' },
      { label: 'Spin Period',    value: '6.2185 ms (161 rotations/sec)' },
      { label: 'Radius',         value: '~10 km' },
      { label: 'Magnetic Field', value: '~8.8 \u00d7 10\u2078 G' },
      { label: 'Char. Age',      value: '~3 billion years' },
      { label: 'Known Planets',  value: '3 \u2014 first exoplanets ever confirmed (1992)' },
      { label: 'Distance',       value: '~2,300 light-years (Virgo)' },
      { label: 'Discovery',      value: 'Wolszczan & Frail, 1992' },
    ],
  },
  'Draugr': {
    type: 'Pulsar Planet (Lowest-mass known)',
    tooltip: [
      { label: 'Mass',   value: '0.020 M\u2295' },
      { label: 'Period', value: '25.26 days' },
      { label: 'Axis',   value: '0.19 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Ultra-low-mass Pulsar Planet' },
      { label: 'Mass',           value: '0.020 M\u2295 (~2\u00d7 Moon mass)' },
      { label: 'Orbital Period', value: '25.262 days' },
      { label: 'Semi-major Axis', value: '0.19 AU' },
      { label: 'Environment',    value: 'Irradiated by pulsar wind' },
      { label: 'Named After',    value: 'An undead creature from Norse mythology' },
      { label: 'Note',           value: 'One of the lowest-mass exoplanets known' },
    ],
  },
  'Poltergeist': {
    type: 'Pulsar Planet (Super-Earth)',
    tooltip: [
      { label: 'Mass',   value: '4.3 M\u2295' },
      { label: 'Period', value: '66.54 days' },
      { label: 'Axis',   value: '0.36 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth Pulsar Planet' },
      { label: 'Mass',           value: '4.3 M\u2295' },
      { label: 'Orbital Period', value: '66.5419 days' },
      { label: 'Semi-major Axis', value: '0.36 AU' },
      { label: 'Environment',    value: 'Irradiated by pulsar wind' },
      { label: 'Named After',    value: 'A type of ghost (noisy spirit)' },
      { label: 'Discovery',      value: 'First confirmed exoplanet (with Phobetor), 1992' },
    ],
  },
  'Phobetor': {
    type: 'Pulsar Planet (Super-Earth)',
    tooltip: [
      { label: 'Mass',   value: '3.9 M\u2295' },
      { label: 'Period', value: '98.21 days' },
      { label: 'Axis',   value: '0.46 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth Pulsar Planet' },
      { label: 'Mass',           value: '3.9 M\u2295' },
      { label: 'Orbital Period', value: '98.2114 days' },
      { label: 'Semi-major Axis', value: '0.46 AU' },
      { label: 'Environment',    value: 'Irradiated by pulsar wind' },
      { label: 'Named After',    value: 'Greek god of nightmares' },
      { label: 'Near Resonance', value: '3:2 with Poltergeist' },
    ],
  },

  // ── WASP-121 system ──
  'WASP-121': {
    type: 'F-type Main Sequence Star (F6V)',
    tooltip: [
      { label: 'Surface Temp', value: '6,460 K' },
      { label: 'Luminosity',   value: '2.10 L\u2609' },
      { label: 'Distance',     value: '~270 ly' },
    ],
    details: [
      { label: 'Classification', value: 'F6V Main Sequence' },
      { label: 'Name',           value: 'Tylos (IAU name)' },
      { label: 'Mass',           value: '1.353 M\u2609' },
      { label: 'Radius',         value: '1.458 R\u2609' },
      { label: 'Surface Temp',   value: '6,460 K' },
      { label: 'Luminosity',     value: '2.10 L\u2609' },
      { label: 'Distance',       value: '~270 light-years (Puppis)' },
      { label: 'Known Planets',  value: '1 (ultra-hot Jupiter)' },
    ],
  },
  'WASP-121b': {
    type: 'Ultra-hot Jupiter',
    tooltip: [
      { label: 'Radius',  value: '1.81 R_J' },
      { label: 'Period',  value: '1.275 days' },
      { label: 'Dayside', value: '~2,500 K' },
    ],
    details: [
      { label: 'Classification',  value: 'Ultra-hot Jupiter' },
      { label: 'Name',            value: 'Kua\u2019kua (IAU name)' },
      { label: 'Mass',            value: '1.183 M_J' },
      { label: 'Radius',          value: '1.81 R_J (highly inflated)' },
      { label: 'Orbital Period',  value: '1.27492 days' },
      { label: 'Semi-major Axis', value: '0.02544 AU' },
      { label: 'Dayside Temp',    value: '~2,500\u20132,700 K' },
      { label: 'Nightside Temp',  value: '~1,800 K' },
      { label: 'Atmosphere',      value: 'H\u2082O, Fe, Mg, Cr, V, TiO detected' },
      { label: 'Tidal Distortion', value: 'Roche lobe fill >1.0 \u2014 egg-shaped' },
      { label: 'Atmospheric Escape', value: 'Heavy metals escaping in comet-like tail' },
    ],
  },

  // ── Proxima Centauri system ──
  'Proxima Centauri': {
    type: 'Red Dwarf Flare Star (M5.5Ve)',
    tooltip: [
      { label: 'Surface Temp', value: '3,042 K' },
      { label: 'Distance',     value: '4.2465 ly' },
      { label: 'Known Planets', value: '3' },
    ],
    details: [
      { label: 'Classification', value: 'M5.5Ve Red Dwarf (UV Ceti flare star)' },
      { label: 'Mass',           value: '0.1221 M\u2609' },
      { label: 'Radius',         value: '0.1542 R\u2609' },
      { label: 'Surface Temp',   value: '3,042 K' },
      { label: 'Luminosity',     value: '0.001567 L\u2609' },
      { label: 'Rotation',       value: '~83 days' },
      { label: 'Known Planets',  value: '3 (d, b, c)' },
      { label: 'Distance',       value: '4.2465 light-years \u2014 nearest star' },
      { label: 'Flare Activity', value: 'Superflares up to ~1000\u00d7 baseline luminosity' },
    ],
  },
  'Proxima d': {
    type: 'Sub-Earth (Hot)',
    tooltip: [
      { label: 'Min. Mass', value: '0.26 M\u2295' },
      { label: 'Period',    value: '5.122 days' },
      { label: 'Axis',      value: '0.029 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Sub-Earth' },
      { label: 'Minimum Mass',   value: '0.26 M\u2295' },
      { label: 'Orbital Period', value: '5.122 days' },
      { label: 'Semi-major Axis', value: '0.02885 AU' },
      { label: 'Habitable Zone', value: 'No \u2014 too hot' },
      { label: 'Discovery',      value: '2022 (radial velocity)' },
      { label: 'Note',           value: 'One of the lightest exoplanets known' },
    ],
  },
  'Proxima b': {
    type: 'Habitable Zone Rocky Planet',
    tooltip: [
      { label: 'Min. Mass', value: '1.07 M\u2295' },
      { label: 'Period',    value: '11.19 days' },
      { label: 'Zone',      value: 'Habitable' },
    ],
    details: [
      { label: 'Classification', value: 'Habitable Zone Rocky' },
      { label: 'Minimum Mass',   value: '1.07 M\u2295' },
      { label: 'Est. Radius',    value: '~1.1 R\u2295' },
      { label: 'Orbital Period', value: '11.186 days' },
      { label: 'Semi-major Axis', value: '0.04857 AU' },
      { label: 'Eq. Temperature', value: '~234 K (-39\u00b0C)' },
      { label: 'Habitable Zone', value: 'Yes \u2014 nearest potentially habitable exoplanet' },
      { label: 'Discovery',      value: '2016 (radial velocity)' },
      { label: 'Concern',        value: 'Stellar flares may strip atmosphere' },
    ],
  },
  'Proxima c': {
    type: 'Super-Earth / Sub-Neptune (Cold)',
    tooltip: [
      { label: 'Min. Mass', value: '~7 M\u2295' },
      { label: 'Period',    value: '~1,928 days' },
      { label: 'Axis',      value: '~1.49 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth / Sub-Neptune' },
      { label: 'Minimum Mass',   value: '~7 M\u2295' },
      { label: 'Est. Radius',    value: '~1.7\u20132.0 R\u2295' },
      { label: 'Orbital Period', value: '~1,928 days (5.28 years)' },
      { label: 'Semi-major Axis', value: '~1.489 AU' },
      { label: 'Habitable Zone', value: 'No \u2014 too cold' },
      { label: 'Discovery',      value: '2020 (radial velocity + astrometry)' },
      { label: 'Status',         value: 'Confirmed but properties uncertain' },
    ],
  },

  // ── Kepler-90 system ──
  'Kepler-90': {
    type: 'Sun-like Star (G0V)',
    tooltip: [
      { label: 'Surface Temp', value: '5,930 K' },
      { label: 'Distance',     value: '2,840 ly' },
      { label: 'Known Planets', value: '8' },
    ],
    details: [
      { label: 'Classification', value: 'G0V Main Sequence' },
      { label: 'Mass',           value: '1.2 M\u2609' },
      { label: 'Radius',         value: '1.2 R\u2609' },
      { label: 'Surface Temp',   value: '5,930 K' },
      { label: 'Luminosity',     value: '~1.2 L\u2609' },
      { label: 'Known Planets',  value: '8 \u2014 most of any known system (tied with Solar System)' },
      { label: 'Distance',       value: '2,840 light-years (Draco)' },
      { label: 'Discovery',      value: 'Kepler mission (2013\u20132017)' },
      { label: 'Note',           value: 'Kepler-90i discovered by Google AI neural network' },
    ],
  },
  'Kepler-90b': {
    type: 'Super-Earth (Hot)',
    tooltip: [
      { label: 'Radius', value: '1.31 R\u2295' },
      { label: 'Period', value: '7.008 days' },
      { label: 'Axis',   value: '0.074 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth' },
      { label: 'Radius',         value: '1.31 R\u2295' },
      { label: 'Orbital Period', value: '7.008 days' },
      { label: 'Semi-major Axis', value: '0.074 AU' },
      { label: 'Eq. Temperature', value: '~1,700 K' },
      { label: 'Habitable Zone', value: 'No \u2014 far too hot' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90c': {
    type: 'Super-Earth (Hot)',
    tooltip: [
      { label: 'Radius', value: '1.18 R\u2295' },
      { label: 'Period', value: '8.719 days' },
      { label: 'Axis',   value: '0.089 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth' },
      { label: 'Radius',         value: '1.18 R\u2295' },
      { label: 'Orbital Period', value: '8.719 days' },
      { label: 'Semi-major Axis', value: '0.089 AU' },
      { label: 'Eq. Temperature', value: '~1,550 K' },
      { label: 'Habitable Zone', value: 'No \u2014 far too hot' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90i': {
    type: 'Super-Earth (Hot) \u2014 AI Discovery',
    tooltip: [
      { label: 'Radius', value: '1.32 R\u2295' },
      { label: 'Period', value: '14.45 days' },
      { label: 'Found',  value: 'Google AI (2017)' },
    ],
    details: [
      { label: 'Classification', value: 'Super-Earth' },
      { label: 'Radius',         value: '1.32 R\u2295' },
      { label: 'Orbital Period', value: '14.45 days' },
      { label: 'Semi-major Axis', value: '0.1234 AU' },
      { label: 'Eq. Temperature', value: '~1,100 K' },
      { label: 'Habitable Zone', value: 'No \u2014 too hot' },
      { label: 'Discovery',      value: '2017 (transit \u2014 Google AI / machine learning)' },
      { label: 'Note',           value: 'First exoplanet discovered by artificial intelligence' },
    ],
  },
  'Kepler-90d': {
    type: 'Sub-Neptune (Warm)',
    tooltip: [
      { label: 'Radius', value: '2.88 R\u2295' },
      { label: 'Period', value: '59.74 days' },
      { label: 'Axis',   value: '0.320 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Sub-Neptune' },
      { label: 'Radius',         value: '2.88 R\u2295' },
      { label: 'Orbital Period', value: '59.74 days' },
      { label: 'Semi-major Axis', value: '0.320 AU' },
      { label: 'Eq. Temperature', value: '~575 K' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90e': {
    type: 'Sub-Neptune (Warm)',
    tooltip: [
      { label: 'Radius', value: '2.67 R\u2295' },
      { label: 'Period', value: '91.94 days' },
      { label: 'Axis',   value: '0.422 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Sub-Neptune' },
      { label: 'Radius',         value: '2.67 R\u2295' },
      { label: 'Orbital Period', value: '91.94 days' },
      { label: 'Semi-major Axis', value: '0.422 AU' },
      { label: 'Eq. Temperature', value: '~500 K' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90f': {
    type: 'Sub-Neptune (Warm)',
    tooltip: [
      { label: 'Radius', value: '2.89 R\u2295' },
      { label: 'Period', value: '124.91 days' },
      { label: 'Axis',   value: '0.480 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Sub-Neptune' },
      { label: 'Radius',         value: '2.89 R\u2295' },
      { label: 'Orbital Period', value: '124.91 days' },
      { label: 'Semi-major Axis', value: '0.480 AU' },
      { label: 'Eq. Temperature', value: '~430 K' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90g': {
    type: 'Gas Giant',
    tooltip: [
      { label: 'Radius', value: '8.13 R\u2295' },
      { label: 'Period', value: '210.60 days' },
      { label: 'Axis',   value: '0.710 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant (sub-Saturn)' },
      { label: 'Radius',         value: '8.13 R\u2295 (~0.73 R\u2643)' },
      { label: 'Orbital Period', value: '210.60 days' },
      { label: 'Semi-major Axis', value: '0.710 AU' },
      { label: 'Eq. Temperature', value: '~330 K' },
      { label: 'Discovery',      value: '2013 (transit)' },
    ],
  },
  'Kepler-90h': {
    type: 'Jupiter-Sized Gas Giant',
    tooltip: [
      { label: 'Radius', value: '11.32 R\u2295' },
      { label: 'Period', value: '331.60 days' },
      { label: 'Axis',   value: '1.01 AU' },
    ],
    details: [
      { label: 'Classification', value: 'Gas Giant (Jupiter-sized)' },
      { label: 'Radius',         value: '11.32 R\u2295 (~1.01 R\u2643)' },
      { label: 'Orbital Period', value: '331.60 days' },
      { label: 'Semi-major Axis', value: '1.01 AU' },
      { label: 'Eq. Temperature', value: '~292 K' },
      { label: 'Discovery',      value: '2013 (transit)' },
      { label: 'Note',           value: 'Outermost known planet \u2014 occupies position similar to Earth' },
    ],
  },

  // ── TOI-700 system ──
  'TOI-700': {
    type: 'Red Dwarf (M2V)',
    tooltip: [
      { label: 'Surface Temp', value: '3,480 K' },
      { label: 'Distance',     value: '101.4 ly' },
      { label: 'Known Planets', value: '4' },
    ],
    details: [
      { label: 'Classification', value: 'M2V Red Dwarf' },
      { label: 'Mass',           value: '0.416 M\u2609' },
      { label: 'Radius',         value: '0.420 R\u2609' },
      { label: 'Surface Temp',   value: '3,480 K' },
      { label: 'Luminosity',     value: '0.023 L\u2609' },
      { label: 'Known Planets',  value: '4 (b, c, e, d)' },
      { label: 'Distance',       value: '101.4 light-years (Dorado)' },
      { label: 'Discovery',      value: 'TESS mission (2020)' },
      { label: 'Note',           value: 'Quiet M-dwarf \u2014 low flare activity, good for habitability' },
    ],
  },
  'TOI-700 b': {
    type: 'Earth-Size (Hot)',
    tooltip: [
      { label: 'Radius', value: '1.01 R\u2295' },
      { label: 'Period', value: '9.977 days' },
      { label: 'Zone',   value: 'Too hot' },
    ],
    details: [
      { label: 'Classification', value: 'Earth-size rocky' },
      { label: 'Radius',         value: '1.01 R\u2295' },
      { label: 'Orbital Period', value: '9.977 days' },
      { label: 'Semi-major Axis', value: '0.0633 AU' },
      { label: 'Habitable Zone', value: 'No \u2014 too hot' },
      { label: 'Discovery',      value: '2020 (TESS transit)' },
    ],
  },
  'TOI-700 c': {
    type: 'Mini-Neptune (Warm)',
    tooltip: [
      { label: 'Radius', value: '2.63 R\u2295' },
      { label: 'Period', value: '16.051 days' },
      { label: 'Zone',   value: 'Warm' },
    ],
    details: [
      { label: 'Classification', value: 'Mini-Neptune' },
      { label: 'Radius',         value: '2.63 R\u2295' },
      { label: 'Orbital Period', value: '16.051 days' },
      { label: 'Semi-major Axis', value: '0.0929 AU' },
      { label: 'Habitable Zone', value: 'No \u2014 interior to HZ' },
      { label: 'Discovery',      value: '2020 (TESS transit)' },
    ],
  },
  'TOI-700 e': {
    type: 'Earth-Size (Habitable Zone)',
    tooltip: [
      { label: 'Radius', value: '0.953 R\u2295' },
      { label: 'Period', value: '28.396 days' },
      { label: 'Zone',   value: 'Habitable (optimistic)' },
    ],
    details: [
      { label: 'Classification', value: 'Earth-size rocky' },
      { label: 'Radius',         value: '0.953 R\u2295' },
      { label: 'Orbital Period', value: '28.396 days' },
      { label: 'Semi-major Axis', value: '0.1340 AU' },
      { label: 'Habitable Zone', value: 'Yes \u2014 optimistic habitable zone' },
      { label: 'Discovery',      value: '2023 (TESS transit)' },
      { label: 'Note',           value: '95% Earth\u2019s size \u2014 smallest HZ planet found by TESS' },
    ],
  },
  'TOI-700 d': {
    type: 'Earth-Size (Habitable Zone)',
    tooltip: [
      { label: 'Radius', value: '1.19 R\u2295' },
      { label: 'Period', value: '37.426 days' },
      { label: 'Zone',   value: 'Habitable (conservative)' },
    ],
    details: [
      { label: 'Classification', value: 'Earth-size rocky' },
      { label: 'Radius',         value: '1.19 R\u2295' },
      { label: 'Orbital Period', value: '37.426 days' },
      { label: 'Semi-major Axis', value: '0.1633 AU' },
      { label: 'Eq. Temperature', value: '~269 K (\u22124\u00b0C)' },
      { label: 'Habitable Zone', value: 'Yes \u2014 conservative habitable zone' },
      { label: 'Discovery',      value: '2020 (TESS transit)' },
      { label: 'Note',           value: 'First Earth-size habitable-zone planet found by TESS' },
    ],
  },

  // ── 51 Pegasi system ──
  '51 Pegasi': {
    type: 'Sun-like Sub-Giant (G2IV)',
    tooltip: [
      { label: 'Surface Temp', value: '5,768 K' },
      { label: 'Distance',     value: '50.45 ly' },
      { label: 'Known Planets', value: '1' },
    ],
    details: [
      { label: 'Classification', value: 'G2IV Sub-Giant (slightly evolved)' },
      { label: 'Mass',           value: '1.11 M\u2609' },
      { label: 'Radius',         value: '1.266 R\u2609' },
      { label: 'Surface Temp',   value: '5,768 K' },
      { label: 'Luminosity',     value: '1.36 L\u2609' },
      { label: 'Metallicity',    value: '[Fe/H] = +0.20 (metal-rich)' },
      { label: 'Known Planets',  value: '1 (51 Peg b "Dimidium")' },
      { label: 'Distance',       value: '50.45 light-years (Pegasus)' },
      { label: 'Note',           value: 'First Sun-like star with a confirmed exoplanet (1995)' },
    ],
  },
  '51 Peg b': {
    type: 'Hot Jupiter \u2014 First Exoplanet',
    tooltip: [
      { label: 'Mass',   value: '0.472 M\u2643' },
      { label: 'Period', value: '4.231 days' },
      { label: 'Temp',   value: '~1,260 K' },
    ],
    details: [
      { label: 'Classification', value: 'Hot Jupiter' },
      { label: 'Formal Name',    value: 'Dimidium (IAU 2015)' },
      { label: 'Mass',           value: '0.472 M\u2643 (150 M\u2295)' },
      { label: 'Est. Radius',    value: '~1.9 R\u2643' },
      { label: 'Orbital Period', value: '4.2308 days' },
      { label: 'Semi-major Axis', value: '0.0527 AU' },
      { label: 'Eq. Temperature', value: '~1,260 K' },
      { label: 'Eccentricity',   value: '0.013 (nearly circular)' },
      { label: 'Discovery',      value: '1995 (radial velocity) \u2014 Mayor & Queloz' },
      { label: 'Significance',   value: 'First exoplanet found around a Sun-like star' },
      { label: 'Nobel Prize',    value: '2019 Physics \u2014 Mayor & Queloz' },
    ],
  },

  // ── Cassiopeia A (Supernova Remnant) ──
  'Cassiopeia A': {
    type: 'Supernova Remnant',
    tooltip: [
      { label: 'Age',      value: '~340 years' },
      { label: 'Distance', value: '11,000 ly' },
      { label: 'Diameter', value: '~16 ly' },
    ],
    details: [
      { label: 'Designation',      value: 'Cas A (3C 461)' },
      { label: 'Type',             value: 'Type IIb Supernova Remnant' },
      { label: 'Supernova Date',   value: '~1681 CE (unobserved)' },
      { label: 'Age',              value: '~340 years' },
      { label: 'Angular Size',     value: "5\u2032 (arcminutes)" },
      { label: 'Diameter',         value: '~16 light-years (5 pc)' },
      { label: 'Expansion Rate',   value: '~5,000 km/s (outer shock)' },
      { label: 'Distance',         value: '11,000 ly (3.4 kpc)' },
      { label: 'Compact Remnant',  value: 'Neutron star (detected in X-ray)' },
      { label: 'Temperature',      value: '~30 million K (shock-heated)' },
      { label: 'Constellation',    value: 'Cassiopeia' },
      { label: 'Discovery',        value: '1947 (radio); 1999 (compact object)' },
    ],
  },

  // ── HL Tauri (Protoplanetary Disk) ──
  'HL Tauri': {
    type: 'T Tauri Star',
    tooltip: [
      { label: 'Age',      value: '~1 Myr' },
      { label: 'Distance', value: '450 ly' },
      { label: 'Disk',     value: '~200 AU diameter' },
    ],
    details: [
      { label: 'Spectral Type',    value: 'K5\u2013K7 (T Tauri)' },
      { label: 'Mass',             value: '~0.55 M\u2609' },
      { label: 'Luminosity',       value: '~3.5 L\u2609' },
      { label: 'Age',              value: '~1 million years' },
      { label: 'Distance',         value: '450 ly (140 pc)' },
      { label: 'Disk Mass',        value: '~0.1 M\u2609' },
      { label: 'Disk Radius',      value: '~100 AU' },
      { label: 'Disk Inclination', value: '46.7\u00B0' },
      { label: 'Gaps Observed',    value: '5+ concentric (ALMA 2015)' },
      { label: 'Jets',             value: 'HH 150/151 (bipolar)' },
      { label: 'Constellation',    value: 'Taurus' },
      { label: 'Cloud',            value: 'Taurus Molecular Cloud (L1551)' },
    ],
  },

  'HL Tau b': {
    type: 'Protoplanet (candidate)',
    tooltip: [
      { label: 'Gap',      value: '#2 (~13 AU)' },
      { label: 'Type',     value: 'Proto-gas giant' },
      { label: 'Status',   value: 'Forming' },
    ],
    details: [
      { label: 'Host Star',     value: 'HL Tauri' },
      { label: 'Orbital Gap',   value: 'Gap 2 (~13 AU)' },
      { label: 'Estimated Mass', value: '~0.3\u20131.0 M\u2C7F (Jupiter masses)' },
      { label: 'Type',          value: 'Proto-gas giant' },
      { label: 'Status',        value: 'Inferred from gap structure' },
      { label: 'Evidence',      value: 'ALMA dust continuum gap' },
    ],
  },

  'HL Tau c': {
    type: 'Protoplanet (candidate)',
    tooltip: [
      { label: 'Gap',      value: '#3 (~32 AU)' },
      { label: 'Type',     value: 'Rocky/icy body' },
      { label: 'Status',   value: 'Forming' },
    ],
    details: [
      { label: 'Host Star',     value: 'HL Tauri' },
      { label: 'Orbital Gap',   value: 'Gap 3 (~32 AU)' },
      { label: 'Estimated Mass', value: '~0.1\u20130.5 M\u2C7F (Jupiter masses)' },
      { label: 'Type',          value: 'Rocky/icy protoplanet' },
      { label: 'Status',        value: 'Inferred from gap structure' },
      { label: 'Evidence',      value: 'ALMA dust continuum gap' },
    ],
  },

  'HL Tau d': {
    type: 'Protoplanet (candidate)',
    tooltip: [
      { label: 'Gap',      value: '#5 (~70 AU)' },
      { label: 'Type',     value: 'Ice giant' },
      { label: 'Status',   value: 'Forming' },
    ],
    details: [
      { label: 'Host Star',     value: 'HL Tauri' },
      { label: 'Orbital Gap',   value: 'Gap 5 (~70 AU)' },
      { label: 'Estimated Mass', value: '~0.2\u20130.5 M\u2C7F (Jupiter masses)' },
      { label: 'Type',          value: 'Proto-ice giant' },
      { label: 'Status',        value: 'Inferred from gap structure' },
      { label: 'Evidence',      value: 'ALMA dust continuum gap' },
    ],
  },

  // ── SGR 1806-20 (Magnetar) ──
  'SGR 1806-20': {
    type: 'Magnetar',
    tooltip: [
      { label: 'B-Field',    value: '~2\u00D710\u00B9\u2075 G' },
      { label: 'Spin Period', value: '7.56 s' },
      { label: 'Distance',   value: '50,000 ly' },
    ],
    details: [
      { label: 'Designation',       value: 'SGR 1806-20' },
      { label: 'Type',              value: 'Soft Gamma Repeater / Magnetar' },
      { label: 'Magnetic Field',    value: '~2\u00D710\u00B9\u2075 G (dipole)' },
      { label: 'Spin Period',       value: '7.5578 s' },
      { label: 'Spin-down Rate',    value: '~2.6\u00D710\u207B\u00B3 s/yr' },
      { label: 'Distance',          value: '~50,000 ly (15.1 kpc)' },
      { label: 'Association',       value: 'Massive star cluster Cl* 1806-20' },
      { label: 'Giant Flare',       value: 'Dec 27, 2004 (peak ~2\u00D710\u2074\u2076 erg/s)' },
      { label: 'Flare Energy',      value: '>3.7\u00D710\u2074\u2076 erg (isotropic)' },
      { label: 'Flare Duration',    value: '~0.2 s spike + 380 s tail' },
      { label: 'Characteristic Age', value: '~600 years' },
      { label: 'Constellation',     value: 'Sagittarius' },
    ],
  },

  // ── GW170817 (Kilonova / Neutron Star Merger) ──
  'GW170817': {
    type: 'Neutron Star Merger',
    tooltip: [
      { label: 'Masses',    value: '1.36 + 1.17 M\u2609' },
      { label: 'Distance',  value: '130 Mly' },
      { label: 'Detected',  value: 'Aug 17, 2017' },
    ],
    details: [
      { label: 'Designation',      value: 'GW170817 / AT 2017gfo / SSS17a' },
      { label: 'Type',             value: 'Binary neutron star merger' },
      { label: 'Component Masses', value: '~1.36 + 1.17 M\u2609 (total ~2.73 M\u2609)' },
      { label: 'Host Galaxy',      value: 'NGC 4993 (elliptical)' },
      { label: 'Distance',         value: '~130 million light-years (40 Mpc)' },
      { label: 'GW Detection',     value: 'LIGO Hanford + Livingston, Virgo' },
      { label: 'GRB',              value: 'GRB 170817A (Fermi GBM, 1.7 s after merger)' },
      { label: 'Kilonova Peak',    value: '~10\u2074\u00B9 erg/s (UV/optical/IR)' },
      { label: 'Ejecta Mass',      value: '~0.05 M\u2609 (r-process material)' },
      { label: 'r-Process Elements', value: 'Gold, platinum, uranium confirmed' },
      { label: 'Significance',     value: 'First multi-messenger GW+EM event' },
      { label: 'Remnant',          value: 'Likely collapsed to black hole' },
    ],
  },

  // ── NGC 6543 (Cat's Eye Nebula) ──
  'NGC 6543': {
    type: 'Planetary Nebula',
    tooltip: [
      { label: 'Type',      value: 'Planetary Nebula' },
      { label: 'Distance',  value: '3,300 ly' },
      { label: 'Star Temp', value: '~80,000 K' },
    ],
    details: [
      { label: 'Designation',       value: 'NGC 6543 / Caldwell 6' },
      { label: 'Common Name',       value: 'Cat\u2019s Eye Nebula' },
      { label: 'Type',              value: 'Planetary nebula' },
      { label: 'Central Star',      value: 'WR-type (Wolf\u2013Rayet features)' },
      { label: 'Star Temperature',  value: '~80,000 K' },
      { label: 'Star Luminosity',   value: '~10,000 L\u2609' },
      { label: 'Nebula Age',        value: '~1,000 years (inner shell)' },
      { label: 'Angular Size',      value: '20\u2033 (inner), 5.8\u2032 (outer halo)' },
      { label: 'Expansion Velocity', value: '~16.4 km/s' },
      { label: 'Distance',          value: '~3,300 light-years' },
      { label: 'Constellation',     value: 'Draco' },
      { label: 'Discovery',         value: 'William Herschel, Feb 15, 1786' },
    ],
  },

  // ── 3C 273 (Quasar / AGN) ──
  '3C 273': {
    type: 'Quasar (Active Galactic Nucleus)',
    tooltip: [
      { label: 'Redshift',   value: 'z = 0.158' },
      { label: 'Distance',   value: '2.4 Gly' },
      { label: 'Luminosity', value: '~4 \u00D7 10\u00B9\u00B2 L\u2609' },
    ],
    details: [
      { label: 'Classification',   value: 'Quasar / Type 1 AGN' },
      { label: 'Black Hole Mass',  value: '~886 million M\u2609' },
      { label: 'Redshift',         value: 'z = 0.158' },
      { label: 'Distance',         value: '2.443 billion light-years' },
      { label: 'Luminosity',       value: '~4 \u00D7 10\u00B9\u00B2 L\u2609 (4 trillion Suns)' },
      { label: 'Apparent Mag',     value: '12.9 (visible in amateur telescopes)' },
      { label: 'Jet Length',       value: '~200,000 light-years' },
      { label: 'Accretion Rate',   value: '~10 M\u2609 per year' },
      { label: 'Variability',      value: 'Days to months (optical)' },
      { label: 'Constellation',    value: 'Virgo' },
      { label: 'Discovery',        value: '1963, Maarten Schmidt (Palomar)' },
    ],
  },

  // ── GRB 221009A (Gamma-Ray Burst) ──
  'GRB 221009A': {
    type: 'Long Gamma-Ray Burst',
    tooltip: [
      { label: 'Nickname', value: '"BOAT" (Brightest Of All Time)' },
      { label: 'Distance', value: '2.4 Gly' },
      { label: 'Duration', value: '~600 s (T90)' },
    ],
    details: [
      { label: 'Designation',       value: 'GRB 221009A / Swift J1913.1+1946' },
      { label: 'Type',              value: 'Long-duration gamma-ray burst' },
      { label: 'Nickname',          value: '"BOAT" \u2014 Brightest Of All Time' },
      { label: 'Redshift',          value: 'z = 0.151' },
      { label: 'Distance',          value: '~2.4 billion light-years (0.74 Gpc)' },
      { label: 'Isotropic Energy',  value: '~10\u2075\u2074 erg (record-breaking)' },
      { label: 'T90 Duration',      value: '~600 seconds' },
      { label: 'Peak Photon Energy', value: '>18 TeV (LHAASO)' },
      { label: 'Jet Lorentz Factor', value: '\u0393 > 100 (~0.9999c)' },
      { label: 'Progenitor',        value: 'Collapsar (massive Wolf\u2013Rayet star)' },
      { label: 'Associated SN',     value: 'SN 2022xiw (Type Ic-BL)' },
      { label: 'Constellation',     value: 'Sagitta' },
      { label: 'Detection Date',    value: 'October 9, 2022' },
    ],
  },

  // ── Crab Pulsar (PSR B0531+21) ──
  'Crab Pulsar': {
    type: 'Pulsar (Neutron Star)',
    tooltip: [
      { label: 'Spin Period', value: '33.5 ms' },
      { label: 'Distance',   value: '6,500 ly' },
      { label: 'Age',        value: '~968 years' },
    ],
    details: [
      { label: 'Designation',     value: 'PSR B0531+21' },
      { label: 'Type',            value: 'Rotation-powered pulsar' },
      { label: 'Spin Period',     value: '33.5 ms (29.9 Hz)' },
      { label: 'Spin-down Rate',  value: '4.2 \u00D7 10\u207B\u00B9\u00B3 s/s' },
      { label: 'Mass',            value: '~1.4 M\u2609' },
      { label: 'Radius',          value: '~10 km' },
      { label: 'Magnetic Field',  value: '3.78 \u00D7 10\u00B9\u00B2 G' },
      { label: 'Distance',        value: '6,500 ly (2.0 kpc)' },
      { label: 'Age',             value: '~968 yr (SN 1054)' },
      { label: 'Spin-down Power', value: '4.6 \u00D7 10\u00B3\u00B8 erg/s' },
      { label: 'Nebula',          value: 'Crab Nebula (M1)' },
      { label: 'Discovery',       value: '1968 (optical pulsations)' },
    ],
  },
};

// Generate satellite data dynamically
for (let i = 1; i <= 5; i++) {
  const alt = (350 + i * 120).toLocaleString();
  const period = (92 + i * 3);
  const inc = [51.6, 98.2, 35.0, 74.1, 20.5][i - 1];
  OBJECT_DATA[`SAT-0${i}`] = {
    type: 'Artificial Satellite',
    tooltip: [
      { label: 'Altitude', value: `${alt} km` },
      { label: 'Orbital Period', value: `${period} min` },
      { label: 'Inclination', value: `${inc}°` },
    ],
    details: [
      { label: 'Classification', value: 'Artificial Satellite' },
      { label: 'Altitude', value: `${alt} km` },
      { label: 'Orbital Period', value: `${period} min` },
      { label: 'Inclination', value: `${inc}°` },
      { label: 'Velocity', value: `${(7.8 - i * 0.1).toFixed(1)} km/s` },
      { label: 'Status', value: 'Operational' },
    ],
  };
}
